<?php
$estruturaColuna = function($label, $coluna_nome) {
    $html = '';
    $html .= "<a href='{$this->url('census', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_nome' => $coluna_nome, 'coluna_sort' => ($this->coluna_nome != $coluna_nome ? 'ASC' : ($this->coluna_sort == 'DESC' ? 'ASC' : 'DESC')), 'itens_pagina' => $this->itens_pagina, 'search' => $this->search]])}'>";
 
    if ($this->coluna_nome == $coluna_nome) {
        $icon = $this->coluna_sort == 'ASC' ? '' : '-alt';
        $html .= "<span class='glyphicon glyphicon-sort-by-attributes{$icon}'></span> ";
    }
 
    $html .= $label;
 
    return $html;
};
?>
<tr>
    <th>
        <?php echo $estruturaColuna('Matricula', 'pol_Matricula'); ?>
    </th>
    <th>
        <?php echo $estruturaColuna('Post/Grad', 'pol_Antiguidade'); ?>
    </th>
    <th>
        <?php echo $estruturaColuna('Nome Guerra', 'pol_NomeGuerra'); ?>
    </th>
    <th>
        <?php echo $estruturaColuna('Celular', 'pol_TelefoneCelular'); ?>.
    </th>
    <th>
        <?php echo $estruturaColuna('Lotação', 'pol_Lotacao'); ?>
    </th> 
    <th class="text-center">Ação</th>  
</tr>