<?php

namespace DoctrineORMModule\Proxy\__CG__\Census\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ferias extends \Census\Entity\Ferias implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'codigo', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao1', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao2', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao3', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'anoreferencia', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'programacao', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'inicio', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'parcela', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'naogozo', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'boletim', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'qtddias', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'polcodigo');
        }

        return array('__isInitialized__', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'codigo', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao1', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao2', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao3', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'anoreferencia', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'programacao', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'inicio', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'parcela', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'naogozo', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'boletim', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'qtddias', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'polcodigo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ferias $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodigo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', array());

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', array($codigo));

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpcao1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpcao1', array());

        return parent::getOpcao1();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpcao1($opcao1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpcao1', array($opcao1));

        return parent::setOpcao1($opcao1);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpcao2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpcao2', array());

        return parent::getOpcao2();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpcao2($opcao2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpcao2', array($opcao2));

        return parent::setOpcao2($opcao2);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpcao3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpcao3', array());

        return parent::getOpcao3();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpcao3($opcao3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpcao3', array($opcao3));

        return parent::setOpcao3($opcao3);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnoreferencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnoreferencia', array());

        return parent::getAnoreferencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnoreferencia($anoreferencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnoreferencia', array($anoreferencia));

        return parent::setAnoreferencia($anoreferencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramacao', array());

        return parent::getProgramacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramacao($programacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramacao', array($programacao));

        return parent::setProgramacao($programacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInicio', array());

        return parent::getInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setInicio($inicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInicio', array($inicio));

        return parent::setInicio($inicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getParcela()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParcela', array());

        return parent::getParcela();
    }

    /**
     * {@inheritDoc}
     */
    public function setParcela($parcela)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParcela', array($parcela));

        return parent::setParcela($parcela);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaogozo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaogozo', array());

        return parent::getNaogozo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaogozo($naogozo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaogozo', array($naogozo));

        return parent::setNaogozo($naogozo);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletim', array());

        return parent::getBoletim();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletim($boletim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletim', array($boletim));

        return parent::setBoletim($boletim);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtddias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtddias', array());

        return parent::getQtddias();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtddias($qtddias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtddias', array($qtddias));

        return parent::setQtddias($qtddias);
    }

    /**
     * {@inheritDoc}
     */
    public function getPolcodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPolcodigo', array());

        return parent::getPolcodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPolcodigo($polcodigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPolcodigo', array($polcodigo));

        return parent::setPolcodigo($polcodigo);
    }

}
