<?php

namespace DoctrineORMModule\Proxy\__CG__\Census\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ferias extends \Census\Entity\Ferias implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'codigo', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao1', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao2', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao3', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'anoreferencia', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'programacao', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'polcodigo');
        }

        return array('__isInitialized__', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'codigo', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao1', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao2', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'opcao3', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'anoreferencia', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'programacao', '' . "\0" . 'Census\\Entity\\Ferias' . "\0" . 'polcodigo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ferias $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getcodigo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getcodigo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcodigo', array());

        return parent::getcodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setcodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setcodigo', array($codigo));

        return parent::setcodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getopcao1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getopcao1', array());

        return parent::getopcao1();
    }

    /**
     * {@inheritDoc}
     */
    public function setopcao1($opcao1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setopcao1', array($opcao1));

        return parent::setopcao1($opcao1);
    }

    /**
     * {@inheritDoc}
     */
    public function getopcao2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getopcao2', array());

        return parent::getopcao2();
    }

    /**
     * {@inheritDoc}
     */
    public function setopcao2($opcao2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setopcao2', array($opcao2));

        return parent::setopcao2($opcao2);
    }

    /**
     * {@inheritDoc}
     */
    public function getopcao3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getopcao3', array());

        return parent::getopcao3();
    }

    /**
     * {@inheritDoc}
     */
    public function setopcao3($opcao3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setopcao3', array($opcao3));

        return parent::setopcao3($opcao3);
    }

    /**
     * {@inheritDoc}
     */
    public function getanoreferencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getanoreferencia', array());

        return parent::getanoreferencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setanoreferencia($anoreferencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setanoreferencia', array($anoreferencia));

        return parent::setanoreferencia($anoreferencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getprogramacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getprogramacao', array());

        return parent::getprogramacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setprogramacao($programacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setprogramacao', array($programacao));

        return parent::setprogramacao($programacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getpolcodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getpolcodigo', array());

        return parent::getpolcodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setpolcodigo($polcodigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setpolcodigo', array($polcodigo));

        return parent::setpolcodigo($polcodigo);
    }

}
