<div class="panel panel-primary">
	<div class="panel-heading">
		<div class="panel-title">
            <h3 class="panel-title">Cadastro de Recurso do Sistema</h3>
        </div>
    </div>
    <div class="panel-body">
    <?php echo $this->form()->openTag($form); ?>
    	<div class="row">
    		
    		<div class="col-xs-6">
    			<?php echo $this->formRow($form->get('perfilcodigo')) ?>
    		</div>
    		<div class="col-xs-6">
    			<?php echo $this->formRow($form->get('nome')) ?>
    		</div>
    	</div>
    </div>
    <div class="panel-footer">
    <?php echo $this->formSubmit($form->get('submit')) ?>
    </div>
    <?php echo $this->form()->closeTag($form); ?> 
</div>