<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->headTitle('SGP '. $this->translate('Gestão de Unidade Policial'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/animate.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/light-bootstrap-dashboard.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/pe-icon-7-stroke.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
 
        <!-- Scripts -->
        <?php
        echo $this
                ->headScript()
                ->appendFile($this->basePath('assets/js/jquery.min.js'))
                ->appendFile($this->basePath('assets/js/jquery-ui.min.js'))
                ->appendFile($this->basePath('assets/js/bootstrap.min.js'))
                // Forms Validations Plugin
                ->appendFile($this->basePath('assets/js/jquery.validate.min.js'))
                // Plugin for Date Time Picker and Full Calendar Plugin
                ->appendFile($this->basePath('assets/js/moment.min.js'))
                // Date Time Picker Plugin is included in this js file
                ->appendFile($this->basePath('assets/js/bootstrap-datetimepicker.js'))
                // Select Picker Plugin
                ->appendFile($this->basePath('assets/js/bootstrap-selectpicker.js'))
                // Checkbox, Radio, Switch and Tags Input Plugins
                ->appendFile($this->basePath('assets/js/bootstrap-checkbox-radio-switch-tags.js'))
                //
                ->appendFile($this->basePath('assets/js/jquery-ui.min.js'))
                // Charts Plugin
                ->appendFile($this->basePath('assets/js/chartist.min.js'))
                // Notifications Plugin
                ->appendFile($this->basePath('assets/js/bootstrap-notify.js'))
                // Sweet Alert 2 plugin
                ->appendFile($this->basePath('assets/js/sweetalert2.js'))
                // Vector Map plugin
                ->appendFile($this->basePath('assets/js/jquery-jvectormap.js'))
                // Wizard Plugin
                ->appendFile($this->basePath('assets/js/jquery.bootstrap.wizard.min.js'))
                // Datatable Plugin
                ->appendFile($this->basePath('assets/js/bootstrap-table.js'))
                // Full Calendar Plugin
                ->appendFile($this->basePath('assets/js/fullcalendar.min.js'))
                // Light Bootstrap Dashboard Core javascript and methods
                ->appendFile($this->basePath('assets/js/light-bootstrap-dashboard.js'))
                // Sharrre Library
                ->appendFile($this->basePath('assets/js/jquery.sharrre.js'))
                ->appendFile($this->basePath('js/jquery.maskedinput.min.js'))
                ->appendFile($this->basePath('js/scripts.js'))
        ;
        
                
 
        echo $this->inlineScript();
        ?>
    </head>
    
    <body>
    	<div class="wrapper">
    		<div class="sidebar" data-color="blue" data-image="<?php echo $this->basePath('assets/img/loboGuara.png') ?>">
    			<div class="sidebar-wrapper">
				<div class="logo">
    					<h2 class="text-center">SGP - BPMA</h2>
    				</div>
				<div class="user">
					<div class="photo">
						<img src="<?php 
						  	if ($this->useridentity()->getPolcodigo()->getFoto())
							{
								echo 'data:' . $this->useridentity()->getPolcodigo()->getFototipo() . ';base64,' . 
								stream_get_contents($this->useridentity()->getPolcodigo()->getFoto());
							} else 
							{
								echo "/assets/img/default-avatar.png";
							}
								?>" />
					</div>
					<div class="info">
						<a data-toggle="collapse" href="#collapseExample"
							class="collapsed">

                        	<?php if ($this->useridentity()):?>
 								<?php 
 									echo $this->useridentity ()->getPolcodigo ()->getPostoGraduacao () . " ";
									echo $this->useridentity ()->getPolcodigo ()->getNomeGuerra ()?>
 							<?php endif;?>
                        
                        <b class="caret"></b>
						</a>
						<div class="collapse" id="collapseExample">
							<ul class="nav">
								<li><a href="#">Perfil</a></li>
								<li><a href="#">Editar Perfil</a></li>
								<li><a href="#">Configurações</a></li>
							</ul>
						</div>
					</div>
				</div>
    					<ul class="nav">
    						<li>                   
                    			<a data-toggle="collapse" href="#componentsCensus">                        
                        			<i class="pe-7s-users"></i> 
                        			<p>Pessoal
                           				<b class="caret"></b>
                        			</p>
                    			</a>                
	                    		<div class="collapse" id="componentsCensus">
	                        		<ul class="nav">
		                            	<li><a href="/mapa">Mapa do Efetivo</a></li>
		                            	<li><a href="/ferias">Férias</a></li>
		                            	<li><a href="/alteracao">Alterações</a></li>
	                        		</ul>
	                    		</div>
                			</li>
                			
                			<li>                   
                    			<a data-toggle="collapse" href="#componentsFormacao">                        
                        			<i class="pe-7s-study"></i> 
                        			<p>Formação
                           				<b class="caret"></b>
                        			</p>
                    			</a>                
	                    		<div class="collapse" id="componentsFormacao">
	                        		<ul class="nav">
		                            	<li><a href="/formacao">Curso Civil</a></li>
		                            	<li><a href="/curso">Curso Militar</a></li>
	                        		</ul>
	                    		</div>
                			</li>
                			
                			<li>                   
                    			<a data-toggle="collapse" href="#componentsSaude">                        
                        			<i class="fa fa-heartbeat"></i> 
                        			<p>Saúde
                           				<b class="caret"></b>
                        			</p>
                    			</a>                
	                    		<div class="collapse" id="componentsSaude">
	                        		<ul class="nav">
		                            	<li><a href="/restricao">Restrições Médicas</a></li>
		                            	<li><a href="/dispensamedica">Dispensas Médicas</a></li>
	                        		</ul>
	                    		</div>
                			</li>
                			
                			<li>                   
                    			<a data-toggle="collapse" href="#componentsMaterial">                        
                        			<i class="pe-7s-albums"></i> 
                        			<p>Patrimônio
                           				<b class="caret"></b>
                        			</p>
                    			</a>                
	                    		<div class="collapse" id="componentsMaterial">
	                        		<ul class="nav">
		                            	<li><a href="/arma">Arma</a></li>
		                            	<li><a href="/ctgrafi">CTGRAFI</a></li>
	                        		</ul>
	                    		</div>
                			</li>
                			
                			<li>                   
                    			<a data-toggle="collapse" href="#componentsProtocolo">                        
                        			<i class="pe-7s-note2"></i> 
                        			<p>Protocolo
                           				<b class="caret"></b>
                        			</p>
                    			</a>                
	                    		<div class="collapse" id="componentsProtocolo">
	                        		<ul class="nav">
		                            	<li><a href="/documento">Tramitação de Documentos</a></li>
		                            	<li><a href="/documento/listararquivados">Documentos Arquivados</a></li>
	                        		</ul>
	                    		</div>
                			</li>
    					</ul>
    				</div>
    			</div>
 			<div class="main-panel">
 				<nav class="navbar navbar-default navbar-fixed">
 					<div class="container-fluid">
 						<div class="navbar-header">
 							<a class="navbar-brand" href="#">Seção Administrativa</a>
 						</div>
 						<div class="collapse navbar-collapse">
 							<ul class="nav navbar-nav navbar-left">
	                        	<li class="dropdown">
	                              	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	                                    Informações do Efetivo
	                                    <b class="caret"></b>
	                              	</a>
	                              	<ul class="dropdown-menu">
		                                <li><a href="/census/aniversariantes">Aniversariantes</a></li>
		                                <li><a href="/census/temposervico">Tempo de Servico</a></li>
		                                <li><a href="/census/bienal">Bienal</a></li>
		                                <li><a href="/census/planodechamada">Plano de Chamada</a></li>
	                              	</ul>
	                        	</li>
		                        <li class="dropdown">
		                         	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		                            	Mapa de Efetivo
		                                	<b class="caret"></b>
		                         	</a>
		            				<ul class="dropdown-menu">
				                    	<li><a href="/mapa">Geral</a></li>
				                    	<li><a href="/mapa/batalhao">Batalhão</a></li>
				                        <li class="divider"></li>
				                        <li><a href="/mapa/goa">GOA</a></li>
				                        <li class="divider"></li>
				                        <li><a href="/mapa">GPTur</a></li>
				                        <li class="divider"></li>
				                        <li><a href="/mapa">Cia Rural Sul</a></li>
				                        <li><a href="/mapa">Cia Rural Leste</a></li>
				                        <li><a href="/mapa">Cia Rural Oeste</a></li>
		                                
		                 			</ul>
	                        	</li>
		                        <li>
		                           <a href="/census">
		                               Consulta ao Efetivo
		                            </a>
		                        </li>
                    		</ul>
		                    <ul class="nav navbar-nav navbar-right">
                    		<?php if ($this->useridentity()->getPercodigo()->getCodigo() == 6):?>
		                    	<li class="dropdown">
		                         	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		                            	Sistema
		                                	<b class="caret"></b>
		                         	</a>
		            				<ul class="dropdown-menu">
				                    	<li><a href="/recurso">Recurso</a></li>
				                    	<li><a href="/perfil">Perfil</a></li>
				                    	<li><a href="/usuario">Usuario</a></li>
		                 			</ul>
	                        	</li>
 								<?php endif;?>
	                        	<li>
	                            	<a href="/user/logout">
	                                	 Sair 
	                            	</a>
	                        	</li> 
	                    	</ul>
 						</div>
 					</div>
 				</nav>
 				<div class="content">
 					<div class="container-fluid">
 						<?php echo $this->content; ?>
 					</div>
 				</div>
 				<footer class="footer">
            		<div class="container-fluid">
                		<nav class="pull-left">
                    		<ul>
                        		<li>
                            		<a href="#">
                                
                            		</a>
                        		</li>
                        		<li>
                            		<a href="#">
                                
                           			</a>
                        		</li>
                        		<li>
                            		<a href="#">
                                
                            		</a>
                        		</li>
                        		<li>
                            		<a href="#">
                               			GurugoNET
                            		</a>
                        		</li>
                    		</ul>
                		</nav>
            		</div>
        		</footer>
 			</div>
  		</div>
	</body>        
</html>
