<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->headTitle('SGP '. $this->translate('Gestão de Unidade Policial'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/animate.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/light-bootstrap-dashboard.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/pe-icon-7-stroke.css')
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
 
        <!-- Scripts -->
        <?php
        echo $this
                ->headScript()
                ->appendFile($this->basePath('assets/js/jquery.min.js'))
                ->appendFile($this->basePath('assets/js/jquery-ui.min.js'))
                ->appendFile($this->basePath('assets/js/bootstrap.min.js'))
                // Forms Validations Plugin
                ->appendFile($this->basePath('assets/js/jquery.validate.min.js'))
                // Plugin for Date Time Picker and Full Calendar Plugin
                ->appendFile($this->basePath('assets/js/moment.min.js'))
                // Date Time Picker Plugin is included in this js file
                ->appendFile($this->basePath('assets/js/bootstrap-datetimepicker.js'))
                // Select Picker Plugin
                ->appendFile($this->basePath('assets/js/bootstrap-selectpicker.js'))
                // Checkbox, Radio, Switch and Tags Input Plugins
                ->appendFile($this->basePath('assets/js/bootstrap-checkbox-radio-switch-tags.js'))
                //
                ->appendFile($this->basePath('assets/js/jquery-ui.min.js'))
                // Charts Plugin
                ->appendFile($this->basePath('assets/js/chartist.min.js'))
                // Notifications Plugin
                ->appendFile($this->basePath('assets/js/bootstrap-notify.js'))
                // Sweet Alert 2 plugin
                ->appendFile($this->basePath('assets/js/sweetalert2.js'))
                // Vector Map plugin
                ->appendFile($this->basePath('assets/js/jquery-jvectormap.js'))
                // Wizard Plugin
                ->appendFile($this->basePath('assets/js/jquery.bootstrap.wizard.min.js'))
                // Datatable Plugin
                ->appendFile($this->basePath('assets/js/bootstrap-table.js'))
                // Full Calendar Plugin
                ->appendFile($this->basePath('assets/js/fullcalendar.min.js'))
                // Light Bootstrap Dashboard Core javascript and methods
                ->appendFile($this->basePath('assets/js/light-bootstrap-dashboard.js'))
                // Sharrre Library
                ->appendFile($this->basePath('assets/js/jquery.sharrre.js'))
                ->appendFile($this->basePath('js/jquery.maskedinput.min.js'))
                ->appendFile($this->basePath('js/scripts.js'))
        ;
        
                
 
        echo $this->inlineScript();
        ?>
    </head>
    
    <body>
    	<div class="wrapper">
    		
 				<div class="content">
 					<div class="container-fluid">
 						<?php echo $this->content; ?>
 					</div>
 				</div>
 			</div>
	</body>        
</html>
