<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->headTitle('SGP '. $this->translate('Gestão de Unidade Policial'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/animate.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/light-bootstrap-dashboard.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/pe-icon-7-stroke.css')
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
 
        <!-- Scripts -->
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/assets/js/bootstrap-checkbox-radio-switch.js')
                ->prependFile($this->basePath() . '/assets/js/bootstrap-notify.js')
                ->prependFile($this->basePath() . '/assets/js/bootstrap-select.js')
                ->prependFile($this->basePath() . '/assets/js/chartist.min.js')
                ->prependFile($this->basePath() . '/assets/js/light-bootstrap-dashboard.js')
                ->prependFile($this->basepath() . '/js/jquery.maskedinput.min.js')
                ->prependFile($this->basePath() . '/js/scripts.js')
                ->prependFile($this->basePath() . '/js/bootstrap-typeahead.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ;
        
                
 
        echo $this->inlineScript();
        ?>
    </head>
    
    <body>
    	<div class="wrapper">
    		<div class="sidebar" data-color="blue" data-image="<?php echo $this->basePath('assets/img/loboGuara.png') ?>">
    			<div class="sidebar-wrapper">
    				<div class="logo">
    					<a href="http://10.201.4.21" class="simple-text">SGP - BPMA</a>
    				</div>
    					<ul class="nav">
    						<li>                   
                    			<a data-toggle="collapse" href="#componentsCensus">                        
                        			<i class="pe-7s-users"></i> 
                        			<p>Census
                           				<b class="caret"></b>
                        			</p>
                    			</a>                
	                    		<div class="collapse" id="componentsCensus">
	                        		<ul class="nav">
		                            	<li><a href="/mapa">Mapa do Efetivo</a></li>
		                            	<li><a href="/ferias">Férias</a></li>
		                            	<li><a href="/alteracao">Alterações</a></li>
	                        		</ul>
	                    		</div>
                			</li>
                			
                			<li>                   
                    			<a data-toggle="collapse" href="#componentsFormacao">                        
                        			<i class="pe-7s-study"></i> 
                        			<p>Formação
                           				<b class="caret"></b>
                        			</p>
                    			</a>                
	                    		<div class="collapse" id="componentsFormacao">
	                        		<ul class="nav">
		                            	<li><a href="/formacao">Curso Civil</a></li>
		                            	<li><a href="/curso">Curso Militar</a></li>
	                        		</ul>
	                    		</div>
                			</li>
                			
                			<li>                   
                    			<a data-toggle="collapse" href="#componentsSaude">                        
                        			<i class="glyphicon glyphicon-heart-empty"></i> 
                        			<p>Saúde
                           				<b class="caret"></b>
                        			</p>
                    			</a>                
	                    		<div class="collapse" id="componentsSaude">
	                        		<ul class="nav">
		                            	<li><a href="/restricao">Restrições Médicas</a></li>
		                            	<li><a href="/dispensamedica">Dispensas Médicas</a></li>
	                        		</ul>
	                    		</div>
                			</li>
                			
                			<li>                   
                    			<a data-toggle="collapse" href="#componentsMaterial">                        
                        			<i class="pe-7s-albums"></i> 
                        			<p>Patrimonio
                           				<b class="caret"></b>
                        			</p>
                    			</a>                
	                    		<div class="collapse" id="componentsMaterial">
	                        		<ul class="nav">
		                            	<li><a href="/arma">Arma</a></li>
		                            	<li><a href="/ctgrafi">CTGRAFI</a></li>
	                        		</ul>
	                    		</div>
                			</li>
    					</ul>
    				</div>
    			</div>
 			<div class="main-panel">
 				<nav class="navbar navbar-default navbar-fixed">
 					<div class="container-fluid">
 						<div class="navbar-header">
 							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#">
 								<span class="sr-only">Toggle navigation</span>
 								<span class="icon-bar"></span>
                        		<span class="icon-bar"></span>
                        		<span class="icon-bar"></span>
 							</button>
 							<a class="navbar-brand" href="#">Seção Administrativa</a>
 						</div>
 						<div class="collapse navbar-collapse">
 							<ul class="nav navbar-nav navbar-left">
	                       		<li>
	                            	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	                                	<i class="fa fa-dashboard"></i>
	                            	</a>
	                        	</li>
	                        	<li class="dropdown">
	                              	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	                                    Informações do Efetivo
	                                    <b class="caret"></b>
	                              	</a>
	                              	<ul class="dropdown-menu">
		                                <li><a href="/census/aniversariantes">Aniversariantes</a></li>
		                                <li><a href="/census/temposervico">Tempo de Servico</a></li>
	                              	</ul>
	                        	</li>
		                        <li>
		                           <a href="">
		                                <i class="fa fa-search"></i>
		                            </a>
		                        </li> 
                    		</ul>
                    
		                    <ul class="nav navbar-nav navbar-right">
		                        <li>
		                           <a href="/census">
		                               Consulta ao Efetivo
		                            </a>
		                        </li>
		                        <li class="dropdown">
		                         	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		                            	Mapa de Efetivo
		                                	<b class="caret"></b>
		                         	</a>
		            				<ul class="dropdown-menu">
				                    	<li><a href="/mapa">Geral</a></li>
				                    	<li><a href="/mapa/batalhao">Batalhão</a></li>
				                        <li class="divider"></li>
				                        <li><a href="/mapa/goa">GOA</a></li>
				                        <li class="divider"></li>
				                        <li><a href="/mapa">GPTur</a></li>
				                        <li class="divider"></li>
				                        <li><a href="/mapa">Cia Rural Sul</a></li>
				                        <li><a href="/mapa">Cia Rural Leste</a></li>
				                        <li><a href="/mapa">Cia Rural Oeste</a></li>
		                                
		                 			</ul>
	                        	</li>
	                        	<li>
	                            	<a href="#">
	                                	<!--  Sair -->
	                            	</a>
	                        	</li> 
	                    	</ul>
 						</div>
 					</div>
 				</nav>
 				<div class="content">
 					<div class="container-fluid">
 						<?php echo $this->content; ?>
 					</div>
 				</div>
 				<footer class="footer">
            		<div class="container-fluid">
                		<nav class="pull-left">
                    		<ul>
                        		<li>
                            		<a href="#">
                                
                            		</a>
                        		</li>
                        		<li>
                            		<a href="#">
                                
                           			</a>
                        		</li>
                        		<li>
                            		<a href="#">
                                
                            		</a>
                        		</li>
                        		<li>
                            		<a href="#">
                               			GurugoNET
                            		</a>
                        		</li>
                    		</ul>
                		</nav>
            		</div>
        		</footer>
 			</div>
  		</div>
	</body>        
</html>
