<div class="panel panel-primary">
	<div class="panel-heading">
		<div class="panel-title">
            Requerimento de parcelamento de férias para <?php echo $dados[0]->getPolcodigo()->getPostograduacao() . " " . $dados[0]->getPolcodigo()->getNomeguerra(); ?>
        </div>
	</div>
	<div class="panel-body">
    <?php $idpolicial = $dados[0]->getPolcodigo()->getCodigo()?>
    
   		<table class="table">
			<thead>
				<tr>
					<th class="text-center">Ref.</th>
					<th class="text-center">Mês</th>
					<th class="text-center">Gozada</th>
					<th class="text-center">Parcela</th>
					<th class="text-center">Início</th>
					<th class="text-center">Qtd Dias</th>
					<th class="text-center">Boletim</th>
					<th class="text-center">Opções</th>
				</tr>
			</thead>
			<tbody>
    				<?php foreach ($dados as $feria):?>
      				<tr>
					<td class="text-center"><?php echo $feria->getAnoreferencia()?></td>
					<td class="text-center"><?php echo $feria->getProgramacao()?></td>
					<td class="text-center"><?php echo $feria->getNaogozo()?></td>
					<td class="text-center"><?php if ($feria->getParcela()) echo $feria->getParcela() . "ª Parcela"?></td>
					<td class="text-center"><?php if ($feria->getInicio()) echo $feria->getInicio()->format('d/m/Y')?></td>
					<td class="text-center"><?php echo $feria->getQtddias()?></td>
					<td class="text-center"><?php echo $feria->getBoletim()?></td>
					<td class="text-center"><a
						href="/ferias/deletar/<?php echo $feria->getCodigo()?>"><i
							style="color: red;" class="glyphicon glyphicon-remove"></i></a></td>
				</tr>
      			<?php endforeach;?>
    		</tbody>
		</table>

		<form action="/requerimento/requererparcelamentoferias/<?php echo $dados[0]->getPolcodigo()->getCodigo();?>" method="POST">
			<div class="container">
				<br>
				<table class="table">
					<tr>
						<th class="text-center">Parcela</th>
						<th>Início</th>
						<th>Qtd Dias</th>
					</tr>
					<tr>
						<td class="text-center">1</td>
						<td><input type="date" name="inicio1" class="form-control"></td>
						<td><input type="text" name="qtddias1" class="form-control"></td>
					</tr>
					<tr id="linha2" style="visibility: hidden;">
						<td class="text-center">2</td>
						<td><input type="date" name="inicio2" class="form-control"></td>
						<td><input type="text" name="qtddias2" class="form-control"></td>
					</tr>
					<tr id="linha3" style="visibility: hidden;">
						<td class="text-center">3</td>
						<td><input type="date" name="inicio3" class="form-control"></td>
						<td><input type="text" name="qtddias3" class="form-control"></td>
					</tr>
					<tr>
						<td colspan="2"><strong>Qtd Parcelas: </strong> <select
							id="parcelas" name="parcelas">
								<option>1</option>
								<option>2</option>
								<option>3</option>
						</select> <strong>&nbsp;&nbsp;&nbsp;Ano Referência: </strong> <select
							id="anoreferencia" name="anoreferencia">
								<option>2014</option>
								<option>2015</option>
								<option>2016</option>
						</select></td>
						<td colspan="2"><strong>Restante: </strong><input type="checkbox"
							name="restante" value="naogozo"> Não gozo </td>
					</tr>
				</table>

	<div class="panel-footer">
		<input type="submit" value="Enviar">
	</div>
			</div>
	
</form>
	</div>
</div>

<script>

//select
var tipo = document.getElementById("parcelas");
var linha1 = document.getElementById("linha1");
var linha2 = document.getElementById("linha2");
var linha3 = document.getElementById("linha3");

// quando o select muda
tipo.onchange = function () {
	var valor = tipo.value;
	if ( valor === "1" ){
		linha2.style.visibility = "hidden";
		linha3.style.visibility = "hidden";
	}
	if ( valor === "2" ){
		linha2.style.visibility = "visible";
		linha3.style.visibility = "hidden";
	}
	if ( valor === "3" ){
		linha2.style.visibility = "visible";
		linha3.style.visibility = "visible";
	}
}
</script>