<div class="panel panel-primary">
	<div class="panel-heading">
		<div class="panel-title">
            Requerimento de parcelamento de férias para <?php echo $dados[0]->getPolcodigo()->getPostograduacao() . " " . $dados[0]->getPolcodigo()->getNomeguerra(); ?>
        </div>
    </div>
	<div class="panel-body">
    <?php $idpolicial = $dados[0]->getPolcodigo()->getCodigo()?>
    
   <table class="table">
				<thead>
					<tr>
						<th class="text-center">Ref.</th>
						<th class="text-center">Mês</th>
						<th class="text-center">Gozada</th>
						<th class="text-center">Parcela</th>
						<th class="text-center">Início</th>
						<th class="text-center">Qtd Dias</th>
						<th class="text-center">Boletim</th>
						<th class="text-center">Opções</th>
					</tr>
				</thead>
				<tbody>
    				<?php foreach ($dados as $feria):?>
      				<tr>
						<td class="text-center"><?php echo $feria->getAnoreferencia()?></td>
						<td class="text-center"><?php echo $feria->getProgramacao()?></td>
						<td class="text-center"><?php echo $feria->getNaogozo()?></td>
						<td class="text-center"><?php if ($feria->getParcela()) echo $feria->getParcela() . "ª Parcela"?></td>
						<td class="text-center"><?php if ($feria->getInicio()) echo $feria->getInicio()->format('d/m/Y')?></td>
						<td class="text-center"><?php echo $feria->getQtddias()?></td>
						<td class="text-center"><?php echo $feria->getBoletim()?></td>
						<td class="text-center"><a href="/ferias/deletar/<?php echo $feria->getCodigo()?>"><i style="color: red;" class="glyphicon glyphicon-remove"></i></a></td>
					</tr>
      			<?php endforeach;?>
    		</tbody>
			</table>
    
    <div class="container"><br>
    
    <table class="table">
    	<tr>
    		<th class="text-center">Parcela</th>
    		<th>Início</th>
    		<th>Qtd Dias</th>
    		<th>Restante</th>
    	</tr>
    	<tr>
    		<td class="text-center">1</td>
    		<td><input type="date" class="form-control"></td>
    		<td><input type="text"  class="form-control"></td>
    		<td><input type="radio" name="restante1"> Não gozo<br>
    		<input type="radio" name="restante1"> Momento oportuno</td>
    	</tr>
    	<tr>
    		<td class="text-center">2</td>
    		<td><input type="date" class="form-control"></td>
    		<td><input type="text"  class="form-control"></td>
    		<td><input type="radio" name="restante2"> Não gozo<br>
    		<input type="radio" name="restante2"> Momento oportuno</td>
    	</tr>
    	<tr>
    		<td class="text-center">3</td>
    		<td><input type="date" class="form-control"></td>
    		<td><input type="text"  class="form-control"></td>
    		<td><input type="radio" name="restante3"> Não gozo<br>
    		<input type="radio" name="restante3"> Momento oportuno</td>
    	</tr>
    </table>
    
	</div></div>
	<div class="panel-footer">
		<input type="submit" value="Enviar" >
	</div>
	</form>
</di