<div class="panel panel-primary">
	<?php echo $this->form()->openTag($form); ?>
	<div class="panel-heading">
		<div class="panel-title">
            <h3 class="panel-title">Cadastro de Formação Civil</h3>
        </div>
    </div>
    <div class="panel-body">
    	<div class="row">
    		
    		<div class="col-xs-4">
    			<?php echo $this->formRow($form->get('areaconhecimento')) ?>
    		</div>
    		<div class="col-xs-5">
    			<?php echo $this->formRow($form->get('instituicao')) ?>
    		</div>
    		<div class="col-xs-3">
    			<?php echo $this->formRow($form->get('conclusao')) ?>
    		</div>
    		
    	</div>
    	<div class="row">
    		<div class="col-xs-4">
    			<?php echo $this->formRow($form->get('tipo')) ?>
    		</div>
    		<div class="col-xs-8">
    			<?php echo $this->formRow($form->get('nome')) ?>
    		</div>
    		<input type="hidden" id="polcodigo" name="polcodigo" value="<?php echo $this->policial['codigo']?>">
    	</div>
    </div>
    <div class="panel-footer">
    <?php echo $this->formSubmit($form->get('submit')) ?>
    </div>
    <?php echo $this->form()->closeTag($form); ?> 
</div>