<div class="panel panel-primary">
	<div class="panel-heading">
        <div class="panel-title">
           <?php if ($dados)echo "Tramitação do Documento"; else echo "Documento não tramitado ainda" ?>
        </div>
    </div>
    <div class="panel-body">
    	<?php if ($dados): ?>
    	
    	<div class="panel panel-default">
    		<div class="panel-body">
    		<div class="row">
    			<div class="col-xs-3">
    				<i>Documento:</i><br><?php echo $dados[0]->getDoccodigo()->getTipo() . " " . $dados[0]->getDoccodigo()->getNumero()?>
    			</div>
    			<div class="col-xs-3">
    				<i>Data:</i><br><?php echo $dados[0]->getDoccodigo()->getData()->format('d/m/Y')?>
    			</div>
    			<div class="col-xs-6">
    				<i>Origem:</i><br><?php echo $dados[0]->getDoccodigo()->getOrigem()?>
    			</div>
    		</div>
    		<br>
    		<div class="row">
    			<div class="col-xs-6">
    				<i>Assunto:</i><br><?php echo $dados[0]->getDoccodigo()->getAssunto()?>
    			</div>
    		</div>   
    		<br>
    		<div class="row">
    			<div class="col-xs-2">
    				<i>Protocolo:</i><br><?php echo str_pad($dados[0]->getDoccodigo()->getProcodigo()->getNumero(), 3, "0", STR_PAD_LEFT);?>
    			</div>
    			<div class="col-xs-2">
    				<i>Data de Recebimento:</i><br><?php echo $dados[0]->getDoccodigo()->getRecebimento()->format('d/m/Y')?>
    			</div>
    		</div>   	
    	</div>
    	</div>
    	
    	<table class="table table-hover table-striped">
    		<thead>
    			<tr>
    				<th>Nº</th>
    				<th>Seção</th>
    				<th>Recebido por</th>
    				<th>Recebido em</th>
    				<th>Tempo na Seção</th>
    				<th>Status</th>
    			</tr>
    		</thead>
    		<tbody>
    		<?php 
    			$dados[] = array('data' => 'fim'); 
    			
    			$counter = 1;
    			$keys = array_keys($dados);
    		?>
    		<?php for ($item = 0; $item < count($keys); $item++):?>
    			<tr>
    				<th><?php echo $counter++?></th>
    				<td><?php echo $dados[$keys[$item]]->getSecao()?></td>
    				<td><?php echo $dados[$keys[$item]]->getPolcodigo()->getPostoGraduacao() . " " . $dados[$keys[$item]]->getPolcodigo()->getNomeGuerra()?></td>
    				<td><?php echo $dados[$keys[$item]]->getData()->format('d/m/Y')?></td>
    				<td><?php 
    					if ($dados[$keys[$item+1]] <> 'fim')
    					{
    						if (is_object($dados[$keys[$item+1]]))
    						{
    							$ultima = $dados[$keys[$item+1]]->getData();
    						} else 
    						{
    							$ultima = new \DateTime();
    							echo $dados[$keys[$item]]->getData()->diff($ultima)->days;
    							
    							if ($dados[$keys[$item]]->getStatus() == "Arquivado")
    							{
    								echo "<td>Arquivado</td></tr>";
    							} else
    							{
    								echo "<td>Local Atual</td></tr>";
    							}
    							break;
    						}
    					}
    					
    					echo $dados[$keys[$item]]->getData()->diff($ultima)->days
    					
    					?></td>
    				<td><?php echo $dados[$keys[$item]]->getStatus()?></td>
    			</tr>
    			<?php 
    			endfor;
    			endif;?>
    		</tbody>
    	</table>
    </div>
    <?php if ($dados):?>
    <div class="panel-footer">
    	<div class="row">
    		<?php if ($this->useridentity()->getPolcodigo()->getLotacao() ==  $dados[$keys[$item]]->getSecao()):?>
    		<div class="col-xs-6 text-center">
    			<?php if ($dados[$keys[$item]]->getStatus() != "Arquivado"):?>
    				<a href="/documento/arquivar/<?php if ($dados) echo $dados[0]->getDoccodigo()->getCodigo()?>"><i class="btn btn-warning glyphicon glyphicon-inbox"> Arquivar</i></a>
    		</div>
    	
    		<div class="col-xs-6 text-center">
    				<a href="/documento/tramitar/<?php if ($dados) echo $dados[0]->getDoccodigo()->getCodigo()?>"><i class="btn btn-success glyphicon glyphicon-step-forward"> Tramitar</i></a>
    			<?php endif;?>
    		</div>
   			<?php endif;?>
    	</div>
    </div>
    <?php endif;?>
</div>

