<div class="card ">
	<div class="header">
		<h4 class="title">Documento</h4>
		<p class="category">Cadastro e edição de documentos</p>
	</div>
	<div class="content">
		<div class="row">
			<div class="col-md-12">
				<?php echo $this->form()->openTag($form); ?>
		    	<div class="row">
					<div class="col-xs-3">
		    			<?php echo $this->formRow($form->get('tipo'))?>
		    		</div>
					<div class="col-xs-2">
		    			<?php echo $this->formRow($form->get('numero'))?>
		    		</div>
					<div class="col-xs-3">
		    			<?php echo $this->formRow($form->get('data'))?>
		    		</div>
					<div class="col-xs-4">
		    			<?php echo $this->formRow($form->get('origem'))?>
		    		</div>
				</div>
				<div class="row">
					<div class="col-xs-9">
		    			<?php echo $this->formRow($form->get('assunto'))?>
		    		</div>
					<div class="col-xs-3">
		    			<?php echo $this->formRow($form->get('recebimento'))?>
		    		</div>
				</div>
			</div>
		</div>
	</div>
	<div class="footer">
		<br>
		<?php echo $this->formSubmit($form->get('submit'))?>
	</div>
	<?php echo $this->form()->closeTag($form); ?> 
</div>