<a href="/documento/adicionar"><button class="btn btn-success btn-fill btn-wd">Novo Documento</button></a>
<br>&nbsp;
<div class="panel panel-primary">
	<div class="panel-heading">
        <div class="panel-title">
            Documentos arquivados
        </div>
    </div>
    <div class="panel-body">
    	<table class="table">
    		<thead>
    			<tr>
    				<th>Nº</th>
    				<th>Documento</th>
    				<th>Data</th>
    				<th>Origem</th>
    				<th>Assunto</th>
    				<th>Recebimento</th>
    				<th>Seção Atual</th>
    				<th>Desde</th>
    				<th>Status</th>
    			</tr>
    		</thead>
    		<tbody>
    		<?php foreach ($dados as $item):?>
    		<?php if ($item['status'] == "Arquivado"):?>
    			<tr>
    				<th><?php echo $item['protocolo']?></th>
    				<td><a href="/documento/detalhar/<?php echo $item['codigo']?>"><?php echo $item['tipo'] . " " . $item['numero']?></a></td>
    				<td><?php echo $item['data']?></td>
    				<td><?php echo $item['origem']?></td>
    				<td><?php echo $item['assunto']?></td>
    				<td><?php echo $item['recebimento']?></td>
    				<td><?php echo $item['secao']?></td>
    				<td><?php echo $item['desde']?></td>
    				<td><?php 
    						if ($item['status'])
    						{
	    						switch ($item['status']) {
	    							case 'Tramitado':
	    								$tramite = "Tramitando";
	    							break;
	    							
	    							case 'Arquivado':
	    								$tramite = "Arquivado";
	    							break;
	    						}
    						} else 
    						{
    							$tramite = "Recebido";
    						}
    						echo $tramite ?></td>
    			</tr>
    			<?php endif;?>
    			<?php endforeach;?>
    		</tbody>
    	</table>
    </div>
    <div class="panel-footer">
    </div>
</div>

