<?php 
//echo "<pre>";
//print_r($policial);
//exit;
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            <div class="campo"><?php echo $this->filter($policial)->postoGraduacao() . " " . $this->filter($policial)->nomeGuerra(); ?></div>
        </div>
        <?php //echo "<pre>"; echo print_r($policial); exit;?>
    </div>
    <div class="panel-body">
    <div class="row">
    <div class="col-xs-8">
	<div class="barra-usuario" data-example-id="nav-pills-with-dropdown">
	    <ul class="nav nav-pills">
	      	<li role="presentation" class="dropdown">
	        	<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
	          Requerimento <span class="caret"></span>
	        	</a>
	        	<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				    <li><a href="/requerimento/abono/<?php echo $this->filter($policial)->codigo(); ?>">Abono de Ponto Anual</a></li>
					<li class="divider"></li>
					<li><a href="/requerimento/reproferias/<?php echo $this->filter($policial)->codigo(); ?>">Reprogramação de Férias</a></li>
					<li><a href="/requerimento/naogozoferias/<?php echo $this->filter($policial)->codigo(); ?>">Não Gozo de Férias</a></li>
					<li><a href="/requerimento/parcelamentoferias/<?php echo $this->filter($policial)->codigo(); ?>">Parcelamento de Férias</a></li>
					<li><a href="/requerimento/gozooportunoferias/<?php echo $this->filter($policial)->codigo(); ?>">Gozo em momento oportuno</a></li>
					<li><a href="/requerimento/interrupcaoferias/<?php echo $this->filter($policial)->codigo(); ?>">Interrupção de Férias</a></li>
					<li class="divider"></li>
					<li><a href="/requerimento/licensaespecial/<?php echo $this->filter($policial)->codigo(); ?>">Licença Especial</a></li>
					<li class="divider"></li>
					<li><a href="#">Ressarcimento de Despesas</a></li>
					<li><a href="#">Inclusão de Dependentes</a></li>
  				</ul>
			</li>
			<li role="presentation" class="dropdown">
	        	<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
	          		Férias <span class="caret"></span>
	        	</a>
	        	<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				    <li><a href="/ferias/adicionar/<?php echo $this->filter($policial)->codigo(); ?>">Programar</a></li>
					<li class="divider"></li>
					<li><a href="#">Indicar Opções</a></li>
  				</ul>
			</li>
			<li role="presentation" class="dropdown">
	        	<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
	          		Formação<span class="caret"></span>
	        	</a>
	        	<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				    <li><a href="/formacao/adicionar/<?php echo $this->filter($policial)->codigo(); ?>">Adicionar Formação</a></li>
					<li class="divider"></li>
					<li><a href="/curso/adicionar/<?php echo $this->filter($policial)->codigo(); ?>">Curso PM</a></li>
  				</ul>
			</li>
			<li role="presentation" class="dropdown">
	        	<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
	          		Saude<span class="caret"></span>
	        	</a>
	        	<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				    <li><a href="/restricao/cadastrar/<?php echo $this->filter($policial)->codigo(); ?>">Restrição Médica</a></li>
					<li class="divider"></li>
					<li><a href="/dispensamedica/cadastrar/<?php echo $this->filter($policial)->codigo(); ?>">Dispensa</a></li>
  				</ul>
			</li>
			<li role="presentation" class="dropdown">
	        	<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
	          		Cautelas <span class="caret"></span>
	        	</a>
	        	<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				    <li><a href="/ctgrafi/adicionar/<?php echo $this->filter($policial)->codigo() ?>">CTGRAF</a></li>
					<li class="divider"></li>
					<li><a href="#">Material</a></li>
  				</ul>
			</li>
			<li role="presentation" class="dropdown">
	        	<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
	          		Alterações <span class="caret"></span>
	        	</a>
	        	<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				    <li><a href="/alteracao/adicionar/<?php echo $this->filter($policial)->codigo() ?>">Punição</a></li>
  				</ul>
			</li>
	    </ul>
	  </div>
	  </div>
	  <div class="col-xs-4">
	    <a href="<?php echo $this->url('census', array('action' => 'editar', 'id' => $this->filter($policial)->codigo())) ?>" class="btn btn-primary btn-sm">Editar Dados</a>
  	  </div>
	  </div>
    
    
    <?php //echo "<pre>"; echo print_r($this->policial);?>
    <br>
    <strong>Dados Pessoais:</strong>
    	<table class="table table-bordered">
    		<tr><td colspan="10"><div class="legenda">Nome Completo:</div><div class="campo"><?php echo $this->filter($policial)->nomeCompleto(); ?></div></td><td colspan="2"><div class="legenda">Quadro:</div><div class="campo"><?php echo $this->filter($policial)->quadro(); ?></div></td></tr>
    		<tr><td colspan="3"><div class="legenda">Matricula:</div><div class="campo"><?php echo $this->filter($policial)->matricula(); ?></div></td><td colspan="4"><div class="legenda">Admissão:</div><div class="campo"><?php echo $this->filter($policial)->dataAdmissao(); ?></div></td><td colspan="2"><div class="legenda">Funcional Validade:</div><div class="campo"><?php echo $this->filter($policial)->identidadeFuncionalValidade(); ?></div></td><td colspan="2"><div class="legenda">Sangue:</div><div class="campo"><?php echo $this->filter($policial)->tipoSangue() ?></div></td><td colspan="2"><div class="legenda">Doador?:</div><div class="campo"><?php echo $this->filter($policial)->doadorSangue() ?></div></td></tr>
    		<tr><td colspan="5"><div class="legenda">CNH:</div><div class="campo"><?php echo $this->filter($policial)->cnhCategoria(); ?></div></td><td><div class="legenda">CNH Validade:</div><div class="campo"><?php echo $this->filter($policial)->cnhValidade(); ?></div></td><td colspan="3"><div class="legenda">TAF Validade:</div><div class="campo"><?php echo $this->filter($policial)->tafValidade(); ?></div></td><td colspan="2"><div class="legenda">Bienal Validade:</div><div class="campo"><?php echo $this->filter($policial)->bienalValidade(); ?></div></td><td colspan="2"><div class="legenda">Porte de Arma:</div><div class="campo"><?php echo $this->filter($policial)->porteArmaSituacao(); ?></div></td></tr>
    	</table>
    <strong>Contato:</strong>
    	<table class="table table-bordered">
    		<tr><td colspan="3"><div class="legenda">Cidade Residência:</div><div class="campo"><?php echo $this->filter($policial)->enderecoCidade() ?></div></td><td colspan="3"><div class="legenda">Celular:</div><div class="campo"><?php echo $this->filter($policial)->telefoneCelular() ?></div></td><td colspan="3"><div class="legenda">Fixo:</div><div class="campo"><?php echo $this->filter($policial)->telefoneFixo() ?></div></td><td colspan="6"><div class="legenda">Email:</div><div class="campo"><?php echo $this->policial->pol_Email ?></div></td></tr>
    	</table>
    <strong>Serviço:</strong>
    	<table class="table table-bordered">
    		<tr><td colspan="3"><div class="legenda">Sub Unidade:</div><div class="campo"><?php echo $this->filter($policial)->subUnidade(); ?></div></td><td colspan="3"><div class="legenda">Lotação:</div><div class="campo"><?php echo $this->filter($policial)->lotacao(); ?></div></td><td colspan="6"><div class="legenda">Posto de Serviço:</div><div class="campo"><?php echo $this->filter($policial)->servicoPosto(); ?></div></td></tr>
    		<tr><td colspan="4"><div class="legenda">Função:</div><div class="campo"><?php echo $this->filter($policial)->servicoFuncao(); ?></div></td><td colspan="4"><div class="legenda">Escala:</div><div class="campo"><?php echo $this->filter($policial)->servicoEscala(); ?></div></td><td colspan="4"><div class="legenda">Horário:</div><div class="campo"><?php echo $this->filter($policial)->servicoHorario(); ?></div></td></tr>
    	</table>
    
    <?php if (count($formacaomilitar) || count($formacaocivil)):?>	
     <strong>Formação:</strong>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>#</th>
					<th>Tipo</th>
					<th>Curso</th>
					<th>Nome</th>
					<th>Conclusão</th>
					<th>Opções</th>
				</tr>
			</thead>
			<tbody>
				<?php $counter = 1;?>
			
				<?php foreach ($formacaomilitar as $militar):?>
				<tr>
					<th scope="row"><?php echo $counter++?></th>
					<td>Militar</td>
					<td><?php echo $militar->getTipo()?></td>
					<td><?php echo $militar->getNome()?></td>
					<td><?php echo $militar->getDataconclusao()->format('Y')?></td>
					<td><a href="/curso/editar/<?php echo $militar->getCodigo()?>"><i class="glyphicon glyphicon-pencil"></i></a> 
    				<a href="/curso/deletar/<?php echo $militar->getCodigo()?>" onClick="deleta()"><i style="color: red;" class="glyphicon glyphicon-remove"></i></a></td>
				</tr>
				<?php endforeach;?>
				
				<?php foreach ($formacaocivil as $civil):?>
				<tr>
					<th scope="row"><?php echo $counter++?></th>
					<td>Civil</td>
					<td><?php echo $civil->getTipo()?></td>
					<td><?php echo $civil->getNome()?></td>
					<td><?php echo $civil->getConclusao()->format('Y')?></td>
					<td><a href="/formacao/editar/<?php echo $civil->getCodigo()?>"><i class="glyphicon glyphicon-pencil"></i></a> 
    				<a href="/formacao/deletar/<?php echo $civil->getCodigo()?>" onClick="deleta()"><i style="color: red;" class="glyphicon glyphicon-remove"></i></a></td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
		<?php endif;?>
		<?php if (count($alteracoes)):?>
		<strong>Alterações:</strong>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>#</th>
					<th>Tipo</th>
					<th>Falta</th>
					<th>Descrição</th>
					<th>Data Fato</th>
					<th>Opções</th>
				</tr>
			</thead>
			<tbody>
				<?php $counter = 1;?>
				<?php foreach ($alteracoes as $alteracao):?>
				<tr>
					<th scope="row"><?php echo $counter++?></th>
					<td><?php echo $alteracao->getTipo()?></td>
					<td><?php echo ($alteracao->getFaltaServico() == '1')? "Sim": "Não"?></td>
					<td><?php echo $alteracao->getDescricao()?></td>
					<td><?php echo $alteracao->getDatafato()->format('d/m/Y')?></td>
					<td><a href="/alteracao/editar/<?php echo $alteracao->getCodigo()?>"><i class="glyphicon glyphicon-pencil"></i></a> 
    				<a href="/alteracao/deletar/<?php echo $alteracao->getCodigo()?>" onClick="deleta()"><i style="color: red;" class="glyphicon glyphicon-remove"></i></a></td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
		<?php endif;?>
		<?php if (count($abonorequerimentos) || count($feriasrequerimentos)):?>
		<strong>Requerimentos:</strong>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>#</th>
					<th>Tipo</th>
					<th>Número</th>
					<th>Solicitação</th>
					<th>Dias</th>
					<th>Início</th>
					<th>Decisão</th>
					<th>Data Decisão</th>
					<th>Opções</th>
				</tr>
			</thead>
			<tbody>
				<?php $counter = 1;?>
				<?php foreach ($abonorequerimentos as $requerimento):?>
				<tr>
					<th scope="row"><?php echo $counter++?></th>
					<td>Abono</td>
					<td><?php echo $requerimento->getNumero()?></td>
					<td><?php echo $requerimento->getDatasolicitacao()->format('d/m/Y')?></td>
					
					<td><?php echo $requerimento->getQuantidadedias()?></td>
					<td><?php echo $requerimento->getInicioabono()->format('d/m/Y')?></td>
					<td><?php 
						if ($requerimento->getDecisao()) 
						{
							echo $requerimento->getDecisao();
						} else {
							echo  "Em tramitação";;
						}
							
						?></td>
					<td><?php 
						if ($requerimento->getDatadecisao())
							echo $requerimento->getDatadecisao()->format('d/m/Y')?></td>
					<td><a href="/requerimento/editarabono/<?php echo $requerimento->getCodigo()?>"><i class="glyphicon glyphicon-pencil"></i></a> 
    				&nbsp;&nbsp; <a href="/requerimento/imprimirabono/<?php echo $requerimento->getCodigo()?>" target="_blank"><i class="glyphicon glyphicon-print"></i></a>
    				<!-- &nbsp;&nbsp; <a href="/requerimento/deletarabono/<?php //echo $requerimento->getCodigo()?>" onClick="deleta()"><i style="color: red;" class="glyphicon glyphicon-remove"></i></a>-->
    				</td>
				</tr>
				<?php endforeach;?>
				
				
				<?php foreach ($feriasrequerimentos as $requerimento):?>
				<tr>
					<th scope="row"><?php echo $counter++?></th>
					<td><?php echo $requerimento->getTipo() ?></td>
					<td><?php echo $requerimento->getNumero() ?></td>
					<td><?php echo $requerimento->getDatasolicitacao()->format('d/m/Y')?></td>
					<td></td>
					<td><?php echo $requerimento->getNovaProgramacao()?></td>
					<td><?php 
						if ($requerimento->getDecisao()) 
						{
							echo $requerimento->getDecisao();
						} else {
							echo  "Em tramitação";;
						}
						
						?></td>
					<td><?php 
						if ($requerimento->getDatadecisao())
							echo $requerimento->getDatadecisao()->format('d/m/Y')?>
							
					</td>
					<td><a href="/requerimento/editarReproFerias/<?php echo $requerimento->getCodigo()?>"><i class="glyphicon glyphicon-pencil"></i></a> 
    				&nbsp;&nbsp; <a href="/requerimento/imprimirReproFerias/<?php echo $requerimento->getCodigo()?>" target="_blank"><i class="glyphicon glyphicon-print"></i></a>
    				<!-- &nbsp;&nbsp; <a href="/requerimento/deletarabono/<?php //echo $requerimento->getCodigo()?>" onClick="deleta()"><i style="color: red;" class="glyphicon glyphicon-remove"></i></a>-->
    				</td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
		<?php endif;?>
	</div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('census', array('action' => 'editar', 'id' => $this->filter($policial)->codigo())) ?>" class="btn btn-primary btn-sm">Editar Dados</a>
        <a href="<?php echo $this->url('census'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>