<style>
#divFoto{
	height: 110px;
	border: 3px ridge;
	width: 90px;
	overflow: hidden;
	position: absolute;
	top: 30px;
	left: 50%;
	margin-left: -50px;
	background-image: url("/assets/img/faces/silhueta.jpg");
	background-size: 90px 110px;
	background-repat: no-repeat;}
</style>

<script>
function preview(input){
    if (input.files && input.files[0])
    {
        var reader = new FileReader();
        reader.onload = function(e)
        {
            $('#preview_image')
            .attr('src', e.target.result)
            .width(90)
            .height(110)
        };
        reader.readAsDataURL(input.files[0]);
    }
}
</script>
<script>
$("#preview_image").click(function() {
    $("input[id='foto']").click();
});
</script>

<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
				<?php echo $this->form()->openTag($form); ?>
					<div class="header">
						<h4 class="title">Cadastro</h4>
						<p class="category">Inclusão de novo policial</p>
					</div>
					<div class="content content-full-width">
						<ul role="tablist" class="nav nav-tabs">
							<li role="presentation" class="active">
								<a href="#icon-info" data-toggle="tab"><i class="fa fa-info"></i> Dados Pessoais</a>
							</li>
							<li><a href="#icon-account" data-toggle="tab">
								<i class="fa fa-user"></i> Contato/Endereço</a>
							</li>
							<li><a href="#icon-style" data-toggle="tab">
								<i class="fa fa-cube"></i> Dados Funcionais</a>
							</li>
						</ul>
						<div class="tab-content">
							<div id="icon-info" class="tab-pane active">
							<div class="panel panel-info">
								<div class="panel-heading">Dados Pessoais:</div>
								<div class="painel-body" style="padding: 5px">
									<!-- Linha 1 do formulário -->
									<div class="row" style="margin-bottom: 10px">
										<div class="col-xs-8 " style="margin-top: 10px"><?php echo $this->formRow($form->get('nomecompleto')) ?></div>
										<div class="col-xs-1"></div>
										<div class="form-group col-md-3">
						<div id="divFoto">
							<label>
							<img id="preview_image" src="<?php 
							  	if ($dataEntity['foto'])
								{
									echo 'data:' . $dataEntity['fototipo'] . ';base64,' . stream_get_contents($dataEntity['foto']);
								} 
								?>" style="position: absolute; width: 100%; height: 100%;" />
							<?php echo $this->formElement($form->get('foto'))?>
							</label>
						</div>
							<?php echo $this->formElementErrors($form->get('foto'))?>
					</div>
									</div>
									<!-- Linha 2 do formulário -->
									<div class="row" style="margin-bottom: 10px">
										<div class="col-xs-3"><?php echo $this->formRow($form->get('cpf')) ?></div>
										<div class="col-xs-3"><?php echo $this->formRow($form->get('rg')) ?></div>
										<div class="col-xs-2"><?php echo $this->formRow($form->get('orgaoexpedidor')) ?></div>
									</div>
									<!-- Linha 3 do formulário -->
									<div class="row" style="margin-bottom: 10px">
										<div class="col-xs-4"><?php echo $this->formRow($form->get('naturalidade')) ?></div>
										<div class="col-xs-3"><?php echo $this->formRow($form->get('naturalidadeuf')) ?></div>
										<div class="col-xs-3"><?php echo $this->formRow($form->get('datanascimento')) ?></div>
										<div class="col-xs-2"><?php echo $this->formRow($form->get('sexo')) ?></div>
									</div>
									<!-- Linha 4 do formulário -->
									<div class="row" style="margin-bottom: 10px">
										<div class="col-xs-4"><?php echo $this->formRow($form->get('estadocivil')) ?></div>
										<div class="col-xs-3"><?php echo $this->formRow($form->get('cnh')) ?></div>
										<div class="col-xs-2"><?php echo $this->formRow($form->get('cnhcategoria')) ?></div>
										<div class="col-xs-3"><?php echo $this->formRow($form->get('cnhvalidade')) ?></div>
									</div>
									<!-- Linha 5 do formulário -->
									<div class="row"  style="margin-bottom: 10px">
										<div class="col-xs-6"><?php echo $this->formRow($form->get('nomepai')) ?></div>
										<div class="col-xs-6"><?php echo $this->formRow($form->get('nomemae')) ?></div>
									</div>
								</div>
								</div>
							</div>
							<div id="icon-account" class="tab-pane">
								<div class="panel panel-info">
									<div class="panel-heading">Contato:</div>
									<div class="painel-body" style="padding: 5px">
										<!-- Linha 1 do formulário -->
										<div class="row" style="margin-bottom: 10px">
											<div class="col-xs-3"><?php echo $this->formRow($form->get('telefonefixo')) ?></div>
											<div class="col-xs-3"><?php echo $this->formRow($form->get('telefonecelular')) ?></div>
											<div class="col-xs-6"><?php echo $this->formRow($form->get('email')) ?></div>
										</div>
									</div>
								</div>
								<div class="panel panel-info">
									<div class="panel-heading">Endereço:</div>
									<div class="painel-body" style="padding: 5px">
										<div class="row" style="margin-bottom: 10px">
											<div class="col-xs-2"><?php echo $this->formRow($form->get('enderecouf')) ?></div>
											<div class="col-xs-4"><?php echo $this->formRow($form->get('enderecocidade')) ?></div>
											<div class="col-xs-3"><?php echo $this->formRow($form->get('enderecobairro')) ?></div>
											<div class="col-xs-3"><?php echo $this->formRow($form->get('enderecoquadra')) ?></div>
										</div>
										<!-- Linha 3 do formulário -->
										<div class="row" style="margin-bottom: 10px">
											<div class="col-xs-4"><?php echo $this->formRow($form->get('enderecoconjunto')) ?></div>
											<div class="col-xs-2"><?php echo $this->formRow($form->get('endereconumero')) ?></div>
											<div class="col-xs-3"><?php echo $this->formRow($form->get('enderecocep')) ?></div>
											<div class="col-xs-3"><?php echo $this->formRow($form->get('enderecotipo')) ?></div>
										</div>
										<!-- Linha 4 do formulário -->
										<div class="row" style="margin-bottom: 10px">
											<div class="col-xs-12"><?php echo $this->formRow($form->get('enderecocomplemento')) ?></div>
										</div>
									</div>
								</div>
							</div>
							<div id="icon-style" class="tab-pane">
								<div class="panel panel-info">
									<div class="panel-heading">Dados Funcionais:</div>
									<div class="painel-body" style="padding: 5px">
										<!-- Linha 1 do formulário -->
										<div class="row" style="margin-bottom: 10px">
											<div class="col-xs-3"><?php echo $this->formRow($form->get('postograduacao')) ?></div>
											<div class="col-xs-3"><?php echo $this->formRow($form->get('nomeguerra')) ?></div>
											<div class="col-xs-2"><?php echo $this->formRow($form->get('matricula')) ?></div>
											<div class="col-xs-2"><?php echo $this->formRow($form->get('matriculasiape')) ?></div>
											<div class="col-xs-2"><?php echo $this->formRow($form->get('comportamento')) ?></div>
										</div>
										<!-- Linha 2 do formulário -->
										<div class="row" style="margin-bottom: 10px">
											<div class="col-xs-3"><?php echo $this->formRow($form->get('dataadmissao')) ?></div>
											<div class="col-xs-2"><?php echo $this->formRow($form->get('quadro')) ?></div>
											<div class="col-xs-2"><?php echo $this->formRow($form->get('antiguidade')) ?></div>
											<div class="col-xs-2"><?php echo $this->formRow($form->get('funcionaltipo')) ?></div>
											<div class="col-xs-3"><?php echo $this->formRow($form->get('identidadefuncionalvalidade')) ?></div>
										</div>
										<!-- Linha 3 do formulário -->
										<div class="row" style="margin-bottom: 10px">
											<div class="col-xs-3"><?php echo $this->formRow($form->get('bienalvalidade')) ?></div>
											<div class="col-xs-3"><?php echo $this->formRow($form->get('tafvalidade')) ?></div>
											<div class="col-xs-2"><?php echo $this->formRow($form->get('tiposangue')) ?></div>
											<div class="col-xs-2"><?php echo $this->formRow($form->get('doadorsangue')) ?></div>
											<div class="col-xs-2"><?php echo $this->formRow($form->get('portearmasituacao')) ?></div>
										</div>
									</div>
								</div>
								<div class="panel panel-info">
									<div class="panel-heading">Dados do Serviço:</div>
									<div class="painel-body" style="padding: 5px">
										<!-- Linha 4 do formulário -->
										<div class="row" style="margin-bottom: 10px">
											<div class="col-xs-4"><?php echo $this->formRow($form->get('subunidade')) ?></div>
											<div class="col-xs-4"><?php echo $this->formRow($form->get('lotacao')) ?></div>
											<div class="col-xs-4"><?php echo $this->formRow($form->get('servicoposto')) ?></div>
										</div>
										<div class="row" style="margin-bottom: 10px">
											<div class="col-xs-4"><?php echo $this->formRow($form->get('servicofuncao')) ?></div>
											<div class="col-xs-4"><?php echo $this->formRow($form->get('servicoescala')) ?></div>
											<div class="col-xs-4"><?php echo $this->formRow($form->get('servicohorario')) ?></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="footer">
						<div class="row">
						<br>
							<div class="col-xs-6 text-center" ><?php echo $this->formSubmit($form->get('submit')) ?></div>
							<div class="col-xs-6 text-center">
								<a href="/census"><button type="button" class="btn btn-default">Voltar</button></a>
							</div>
						</div>
					</div>
				<?php echo $this->form()->closeTag($form); ?>
				</div>
			</div>
		</div>
	</div>
</div>



<script>

//select
var tipo = document.getElementById("funcionaltipo");
var validadefuncional = document.getElementById("identidadefuncionalvalidade");

// quando o select muda
tipo.onchange = function () {
	var valor = tipo.value;
	if ( valor === "I" ){
		validadefuncional.disabled = true;
	}
}
</script>