<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            <div class="campo">Plano de Chamada</div>
        </div>
    </div>
	<div class="panel-body">
		<table class="table">
		<tr>
				<th>Nº</th>
				<th>Policial</th>
				<th>Telefones</th>
				<th>Cidade de Residência</th>
				<th>Sub Unidade</th>
			</tr>
			<?php 
			$counter = 1;
			$hoje = new \DateTime()?>
			<?php foreach ($policiais as $item):?>
			
			<tr>
				<td><?php echo $counter++?></td>
				<td><?php echo $item['postograduacao'] . " " . $item['nomeguerra']?></td>
				<td><?php echo $item['telefonefixo'] . "  " . $item['telefonecelular']?></td>
				<td><?php echo $item['enderecocidade'] . "-" . $item['enderecouf'] ?></td>
				<td><?php 
					switch ($item['subunidade']) {
						case 'Btl':
						 	$item['subunidade'] = 'Batalhão';
						break;
					}
				echo $item['subunidade']?></td>
			<?php endforeach;?>
			</tr>
		</table>
	</div>
</div>