<div class="card ">
	<div class="header">
		<h4 class="title">Bienal</h4>
		<p class="category">Situação atual dos policiais</p>
	</div>
	<div class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="table-responsive"></div>
				<table class="table table-condensed table-striped table-hover">
					<tr>
						<th>Nº</th>
						<th>Matrícula</th>
						<th>Post/Grad</th>
						<th>Nome Completo</th>
						<th>Telefones</th>
						<th>Endereço</th>
						<th>SubUnidade</th>
					</tr>
					<?php 
					$counter = 1;
					$hoje = new \DateTime()?>
					<?php foreach ($policiais as $item):?>
					
					<tr>
						<td><?php echo $counter++?></td>
						<td> <a href="/census/detalhes/<?php echo $item['codigo']?>">
							<?php echo $item['matricula']?></a></td>
						<td><?php echo $item['postograduacao'] . " " . $item['quadro']?></td>
						<td><?php echo $item['nomecompleto']?></a>
						</td>
						<td><?php echo $item['telefonefixo'] . "  " . $item['telefonecelular']?></td>
						<td><?php echo $item['enderecoquadra'] . " " . $item['enderecoconjunto'] . ", ".  $item['endereconumero'] . " - "  . $item['enderecocidade'] . "-" . $item['enderecouf']?></td>
						<td><?php
							if ($item['subunidade'] == "Btl") 
    				    		{
    				    			echo "Batalhão"; 
    				    		} else 
    				    		{ 
    				    			echo $item['subunidade'];
    				    		} ; ?></td>
					<?php endforeach;?>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>