<table class="table">

	<?php 
	$counter = 1;
	$hoje = new \DateTime()?>
	<?php foreach ($policiais as $item):?>
	<tr>
		<td><?php echo $counter++?></td>
		<td><?php echo $item['postograduacao'] . " " . $item['nomeguerra']?></td>
		<td><?php $temposervico = $hoje->diff($item['dataadmissao']); echo "{$temposervico->y} anos, {$temposervico->m} meses e {$temposervico->d} dias";?></td>
		<td><?php $idade = $hoje->diff($item['datanascimento']); echo "{$idade->y} anos"?></td>
	<?php endforeach;?>
	</tr>
</table>