<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            <div class="campo">Tempo de Serviço do Efetivo do BPMA</div>
        </div>
    </div>

<table class="table">
<tr>
		<th>Nº</th>
		<th>Policial</th>
		<th>Tempo de Serviço</th>
		<th>Idade</th>
	</tr>
	<?php 
	$counter = 1;
	$hoje = new \DateTime()?>
	<?php foreach ($policiais as $item):?>
	
	<tr>
		<td><?php echo $counter++?></td>
		<td><?php echo $item['postograduacao'] . " " . $item['nomeguerra']?></td>
		<td><?php $temposervico = $hoje->diff($item['dataadmissao']); echo "{$temposervico->y} anos, {$temposervico->m} meses e {$temposervico->d} dias";?></td>
		<td><?php $idade = $hoje->diff($item['datanascimento']); echo "{$idade->y} anos"?></td>
	<?php endforeach;?>
	</tr>
</table>