<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="../../assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Sistema de Gestão Policial Militar</title>

	<!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->appendStylesheet($this->basePath('/assets/css/bootstrap.min.css'))
                        ->appendStylesheet($this->basePath('/assets/css/light-bootstrap-dashboard.css'))
                        ->appendStylesheet($this->basePath('/assets/css/pe-icon-7-stroke.css'))

        ?>
      
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>

	<!-- Scripts -->
        <?php
        echo $this->headScript()
                ->appendFile($this->basePath() . '/assets/js/jquery.min.js')
                ->appendFile($this->basePath() . '/assets/js/jquery-ui.min.js')
                ->appendFile($this->basePath() . '/assets/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/assets/js/light-bootstrap-dashboard.js');
        
        echo $this->inlineScript();
        ?>

</head>
<body> 

<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container">    
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Sistema de Gestão Policial Militar</a>
        </div>
        <div class="collapse navbar-collapse">       
            
            <ul class="nav navbar-nav navbar-right">
                <li>
                   <a href="#">
                        Registro
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="wrapper wrapper-full-page">
    <div class="full-page login-page" data-color="blue" data-image="../../assets/img/full-screen-image-1.jpg">   
        
    <!--   you can change the color of the filter page using: data-color="blue | azure | green | orange | red | purple" -->
        <div class="content">
            <div class="container">
                <?php echo $this->content; ?>
            </div>
        </div>
    	
    	<footer class="footer footer-transparent">
            <div class="container">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                PMDF
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                BPMA
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Seção Administrativa
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy; 2015 <a href="#">GurugoNET</a>, fazendo o que já deveria ter sido feito
                </p>
            </div>
        </footer>

    </div>                             
       
</div>

</body>
    
    
	
    <script type="text/javascript">
        $().ready(function(){
            lbd.checkFullPageBackgroundImage();
            
            setTimeout(function(){
                // after 1000 ms we add the class animated to the login/register card
                $('.card').removeClass('card-hidden');
            }, 700)
        });
    </script>
</html>

