<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card ">
				<div class="header">
					<h4 class="title">Férias 2016</h4>
					<p class="category">Distribuição das férias do efetivo do BPMA referente ao ano de 2015</p>
				</div>
				<div class="content">
					<div class="row">
						<div class="col-md-12">
							<div class="table-responsive">
								<table class="table">
									<thead>
										<tr>
											<th>Situação</th>
											<th>Jan</th>
											<th>Fev</th>
											<th>Mar</th>
											<th>Abr</th>
											<th>Mai</th>
											<th>Jun</th>
											<th>Jul</th>
											<th>Ago</th>
											<th>Set</th>
											<th>Out</th>
											<th>Nov</th>
											<th>Dez</th>
											<th>Total</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>Previsão</td>
											<td class="text-center"><a href="/ferias/listar?mes=JAN"><?php echo $resumoFerias['JAN']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=FEV"><?php echo $resumoFerias['FEV']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=MAR"><?php echo $resumoFerias['MAR']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=ABR"><?php echo $resumoFerias['ABR']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=MAI"><?php echo $resumoFerias['MAI']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=JUN"><?php echo $resumoFerias['JUN']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=JUL"><?php echo $resumoFerias['JUL']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=AGO"><?php echo $resumoFerias['AGO']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=SET"><?php echo $resumoFerias['SET']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=OUT"><?php echo $resumoFerias['OUT']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=NOV"><?php echo $resumoFerias['NOV']?></a></td>
											<td class="text-center"><a href="/ferias/listar?mes=DEZ"><?php echo $resumoFerias['DEZ']?></a></td>
											<th class="text-center"><?php
											
echo $resumoFerias ['JAN'] + $resumoFerias ['FEV'] + $resumoFerias ['MAR'] + $resumoFerias ['ABR'] + $resumoFerias ['MAI'] + $resumoFerias ['JUN'] + $resumoFerias ['JUL'] + $resumoFerias ['AGO'] + $resumoFerias ['SET'] + $resumoFerias ['OUT'] + $resumoFerias ['NOV'] + $resumoFerias ['DEZ']?></th>
										</tr>
										<tr>
											<td>Gozadas</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
										</tr>
										<tr>
											<td>Não gozadas</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
											<td class="text-center">0</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>					
					</div>
				</div>
			</div>
		</div>
	</div>



	<div class="row">
		<div class="col-md-4">
			<div class="card">
				<div class="header">
					<h4 class="title">Férias Gozadas</h4>
					<p class="category">Controle por subunidade</p>
				</div>
				<div class="content">
					Conteúdo
				</div>
				<div class="footer">
					<div class="legend">
						<i class="fa fa-circle text-info"></i> Open <i
							class="fa fa-circle text-danger"></i> Bounce <i
							class="fa fa-circle text-warning"></i> Unsubscribe
					</div>
				</div>

			</div>
		</div>

		<div class="col-md-8">
			<div class="card">
				<div class="header">
					<h4 class="title">Férias 2016</h4>
					<p class="category">Distribuição no ano</p>
				</div>
				<div class="content">
					<div class="ct-chart ct-perfect-fourth"></div>
				</div>
				<div class="footer">
					<div class="legend">
						<i class="fa fa-circle text-info"></i> Policiais programados 
						<i class="fa fa-circle text-danger"></i> Efetivo máximo permitido 
					</div>
				</div>
			</div>
		</div>
	</div>
</div>  

<script type="text/javascript">
  var data = {
		  // A labels array that can contain any sort of values
		  labels: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
		  // Our series array that contains series objects or in this case series data arrays
		  series: [
		    [	<?php echo $resumoFerias['JAN']?>, 
		    	<?php echo $resumoFerias['FEV']?>, 
		    	<?php echo $resumoFerias['MAR']?>,
		    	<?php echo $resumoFerias['ABR']?>, 
		    	<?php echo $resumoFerias['MAI']?>, 
		    	<?php echo $resumoFerias['JUN']?>,
		    	<?php echo $resumoFerias['JUL']?>, 
		    	<?php echo $resumoFerias['AGO']?>, 
		    	<?php echo $resumoFerias['SET']?>,
		    	<?php echo $resumoFerias['OUT']?>, 
		    	<?php echo $resumoFerias['NOV']?>, 
		    	<?php echo $resumoFerias['DEZ']?>,
			],
			[42,42,42,42,42,42,42,42,42,42,42,42]
		  ]
		};
  		var options = {

		};

		// Create a new line chart object where as first parameter we pass in a selector
		// that is resolving to our chart container element. The Second parameter
		// is the actual data object.
		new Chartist.Bar('.ct-chart', data, options);
</script>
