<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card ">
				<div class="header">
					<h4 class="title">Relação de policiais de férias</h4>
					<p class="category"><?php echo "Programação para " . $_GET['mes'] . "/2016" ?></p>
				</div>
				<div class="content">
					<div class="row">
						<div class="col-md-12">
							<div class="table-responsive">
								<table class="table table-striped table-hover">
									<thead>
										<tr>
											<th>Nº</th>
											<th class="text-center">Matricula</th>
											<th>Policial</th>
											<th class="text-center">Celular</th>
											<th>SubUnidade</th>
											<th>Lotação</th>
											<th class="text-center">Ação</th>
										</tr>
									</thead>

									<tbody>
        								<?php $counter = 1;?>
            							<?php foreach ($this->lista as $pessoa) : ?>
        								<tr>
        									<td><?php echo $counter++ ?></td>
											<td class="text-center"><?php echo $pessoa['matricula']; ?></td>
											<td><?php echo $pessoa['postograduacao'] . ' ' . $pessoa['nomeguerra']; ?></td>
											<td class="text-center"><?php echo $pessoa['telefonecelular']; ?></td>
											<td><?php echo $pessoa['subunidade']; ?></td>
											<td><?php echo $pessoa['lotacao']; ?></td>
											<td class="text-center"><a class="btn btn-xs btn-info"
												href="<?php echo $this->url('census', array("action" => "detalhes", "id" => $pessoa['codigo'])); ?>"
												title="Visualizar"><span
													class="glyphicon glyphicon-new-window"></span></a></td>
										</tr>
    									<?php endforeach; ?>
        							</tbody>
								</table>
								<br>
								<a href="<?php echo $this->url('ferias', array('action' => 'index'))?>" class="btn btn-success" title="Novo">
									Voltar
							    </a>
							</div>
						</div>					
					</div>
				</div>
			</div>
		</div>
	</div>
</div>  

