<div class="corpo-table">
<?php 
	/* echo "<pre>";
	print_r($lista);
	exit; */
?>
			<div class="panel-heading">
                <h3 class="panel-title"><?php echo "Férias programadas para " . $_GET['mes'] . "/2016" ?></h3>
            </div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
			<tr>
			    <th>Matricula</th>
			    <th>Post/Grad</th>
			    <th>Nome Guerra</th>
			    <th>Celular</th>
			    <th>Lotação</th> 
			    <th>Ação</th>  
			</tr>
        </thead>
 
        <tbody>
        	<?php //echo "<pre>"; print_r($this->lista);exit;?>
            <?php foreach ($this->lista as $pessoa) : ?>
        	<tr>
            <td class="text-center"><?php echo $pessoa['matricula']; ?></td>
			<td><?php echo $pessoa['postograduacao']; ?></td>
			<td><?php echo $pessoa['nomeguerra']; ?></td>
			<td><?php echo $pessoa['telefonecelular']; ?></td>
			<td><?php echo $pessoa['lotacao']; ?></td>
            <td>
                <button class="btn btn-xs btn-info" data-toggle="modal" data-target="#modal-detalhes-contato" data-contato-url="<?php echo $this->url('census', array("action" => "detalhes", "id" => $pessoa['codigo'])); ?>" title="Visualizar" ><span class="glyphicon glyphicon-new-window"></span></button>
            </td>
        </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
</div>	

	<div class="modal fade" id="modal-detalhes-contato">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                Corpo Modal Detalhes Policial
            </div>
          </div>
    </div>
	

</div>
<?php $this->headScript()->captureStart(); ?>
$(function(){
    // variável para conter a url deletar
    var url_deletar     = '<?php echo $this->url('census', array("action" => "deletar")); ?>' + '/';
 
    // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
    $("a[href*='" + url_deletar + "']").click(function (event) {
        // variável contendo o id referente ao botão clicado
        var contato_id  = $(this).attr('href').split(url_deletar).pop();
        // variável contendo mensagem da janela
        var mensagem = "Deseja realmente apagar o policial de ID " + contato_id + "?";
        // variável com resposta da mensagem colocada na janela
        var confirmacao = confirm(mensagem);
 
        // se a confirmação for false o fluxo é interrompido
        if (!confirmacao)
            // elimar o evendo do botão clicado
            event.preventDefault();
    });
});

$(function(){
    $('#modal-detalhes-contato').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)             // Button that triggered the modal
        var contato_url = button.data('contato-url')    // Extract info from data-* attributes
        
        var modal = $(this)
        modal.
            find('.modal-body').        // localizar corpo modal
            html('Carregando...').      // colocar html caso a requição demore
            load(contato_url)           // inserir conteudo html AJAX
    })
});

<?php $this->headScript()->captureEnd(); ?>

<a href="<?php echo $this->url('ferias', array('action' => 'index'))?>" class="btn btn-success" title="Novo">
Voltar
    </a>