<div class="panel panel-primary">
	<div class="panel-heading">
        <div class="panel-title">
            Cadastro de Restrição Médica para <?php echo $this->policial['postograduacao'] . " " . $this->policial['nomeguerra']?>
        </div>
    </div>
    <div class="panel-body">
    
    <table class="table">
    	<tr>
    		<th>Nº</th>
    		<th>Início</th>
    		<th>Fim</th>
    		<th>Restrições</th>
    		<th>Opções</th>
    	</tr>
    	<?php $counter = 1;?>
    	<?php foreach ($restricoes as $restricao):?>
    	<tr>
    		<td><?php echo $counter++?></td>
    		<td><?php echo $restricao->getInicio()->format('d/m/Y')?></td>
    		<td><?php echo $restricao->getFim()->format('d/m/Y')?></td>
    		<td><?php foreach ($restricao->getRetcodigo() as $var)
          					{
          						$desc = $var->getDescricao();
          						$tipo = $var->getTipo();
          						
          						echo "<i title='$desc'>$tipo </i>";
          					}?></td>
    		<td><a href="/restricao/deletar/<?php echo $restricao->getRescodigo()?>"><i class="glyphicon glyphicon-trash" style="color: red"></i></a></td>
    			</td>
    	</tr>
    	<?php endforeach;?>
    </table>
    
    <?php echo $this->form()->openTag($form); ?>
    	<div class="row">
    		<div class="col-xs-3">
    			<?php echo $this->formRow($form->get('inicio')) ?>
    		</div>
    		
    		<div class="col-xs-3">
    			<?php echo $this->formRow($form->get('fim')) ?>
    		</div>
    		
    		<div class="col-xs-3">
    			<?php echo $this->formRow($form->get('retcodigo')) ?>
    		</div>
    	</div>
    	<input type="hidden" id="polcodigo" name="polcodigo" value="<?php echo $this->policial['codigo']?>">
    </div>
    <div class="panel-footer">
    <?php echo $this->formSubmit($form->get('submit')) ?>
    </div>
    <?php echo $this->form()->closeTag($form); ?> 
</div>