<div class="panel panel-primary">
	<div class="panel-heading">
        <div class="panel-title">
            Restrições Médicas
        </div>
    </div>
    <div class="panel-body">
    <a href="/restricao/cadastrar"><button type="button" class="btn btn-default navbar-btn">Nova Restrição</button></a>
    </div>
    <div class="panel-body">
    	<table class="table">
    		<thead>
    			<tr>
    				<th>Codigo</th>
    				<th>Descrição</th>
    				<th>Opções</th>
    			</tr>
    		</thead>
    		<tbody>
    		<?php foreach ($dados as $item):?>
    			<tr>
    				
    				<td><?php echo $item->getTipo()?></td>
    				<td><?php echo $item->getDescricao()?></td>
    				<td><a href="/restricao/editar/<?php echo $item->getCodigo()?>"><i class="glyphicon glyphicon-pencil"></i></a> 
    				<a href="/restricao/deletar/<?php echo $item->getCodigo()?>" onClick="deleta()"><i style="color: red;" class="glyphicon glyphicon-remove"></i></a></td>
    				
    			</tr>
    			<?php endforeach;?>
    		</tbody>
    	</table>
    </div>
    <div class="panel-footer">
    </div>
</div>

<script>
	function deleta(){
		if(confirm("Tem certeza que deseja excluir este registro?")){
			return true;
		} else {
			return false;
		}
}
</script>