<div class="panel panel-primary">
	<div class="panel-heading">
        <div class="panel-title">
            Restrições Médicas Vigentes
        </div>
    </div>
    <div class="panel-body">
    	<table class="table">
    		<thead>
    			<tr>
    				<th>Post/Grad</th>
    				<th>Nome de Guerra</th>
    				<th>Início</th>
    				<th>Fim</th>
    				<th>Restrições</th>
    				<th>Opções</th>
    			</tr>
    		</thead>
    		<tbody>
    		<?php $counter = 1;?>
    		<?php foreach ($dados as $item):?>
    		<?php 
    				$today = new \DateTime('now');
    			if ($item->getInicio() <= $today && $today <= $item->getFim()):?>
    			<tr>
    				<td><?php echo $counter++ ?></td>
    				<td><a href="/census/detalhes/<?php echo $item->getPolcodigo()->getCodigo()?>">
    				    	<i title="<?php 
    				    		if ($item->getPolcodigo()->getSubunidade() == "Btl") 
    				    		{
    				    			$class="Batalhão"; 
    				    		} else 
    				    		{ 
    				    			$class = $item->getPolcodigo()->getSubunidade();
    				    		} ; 
    				    		echo $class ? $class : "Sem Classificação"; 
    				    		echo ($item->getPolcodigo()->getServicoposto()) ? " - " . $item->getPolcodigo()->getServicoposto() : " - Sem local"; 
    				    		echo ($item->getPolcodigo()->getServicofuncao()) ? " - " . $item->getPolcodigo()->getServicofuncao() : " - Sem função"?>">
    				    		<?php echo $item->getPolcodigo()->getPostoGraduacao() . " " .$item->getPolcodigo()->getNomeGuerra()?>
    				    	</i>
    				    </a>
    				</td>
    				<td><?php echo $item->getInicio()->format('d/m/Y');?></td>
    				<td><?php echo $item->getFim()->format('d/m/Y');?></td>
    				<td><?php 
          					foreach ($item->getRetcodigo() as $var)
          					{
          						$desc = $var->getDescricao();
          						$tipo = $var->getTipo();
          						
          						echo "<i title='$desc'>$tipo </i>";
          					}
            //echo $item->getRetcodigo()->getTipo()?></td>
            		<td><a href="/restricao/alterar/<?php echo $item->getRescodigo()?>"><i class="glyphicon glyphicon-pencil"></i></a> 
    				<a href="/restricao/deletar/<?php echo $item->getRescodigo()?>"><i class="glyphicon glyphicon-trash" style="color: red"></i></a></td>
    			</tr>
    			<?php endif;?>
    			<?php endforeach;?>
    		</tbody>
    	</table>
    </div>
    <div class="panel-footer">
    </div>
</div>


<div class="panel panel-primary">
	<div class="panel-heading">
        <div class="panel-title">
            Restrições Médicas
        </div>
    </div>
    <div class="panel-body">
    	<table class="table">
    		<thead>
    			<tr>
    				<th>Post/Grad</th>
    				<th>Nome de Guerra</th>
    				<th>Início</th>
    				<th>Fim</th>
    				<th>Restrições</th>
    				<th>Opções</th>
    			</tr>
    		</thead>
    		<tbody>
    		<?php $counter = 1;?>
    		<?php foreach ($dados as $item):?>
    			<tr>
    				<td><?php echo $counter++ ?></td>
    				<td><a href="/census/detalhes/<?php echo $item->getRescodigo()?>"><?php echo $item->getPolcodigo()->getPostoGraduacao() . " " . $item->getPolcodigo()->getNomeGuerra()?></a></td>
    				<td><?php echo $item->getInicio()->format('d/m/Y');?></td>
    				<td><?php echo $item->getFim()->format('d/m/Y');?></td>
    				<td><?php 
          					foreach ($item->getRetcodigo() as $var)
          					{
          						$desc = $var->getDescricao();
          						$tipo = $var->getTipo();
          						
          						echo "<i title='$desc'>$tipo </i>";
          					}
            //echo $item->getRetcodigo()->getTipo()?></td>
            		<td><a href="/restricao/alterar/<?php echo $item->getRescodigo()?>"><i class="glyphicon glyphicon-pencil"></i></a> 
    				<a href="/restricao/deletar/<?php echo $item->getRescodigo()?>"><i class="glyphicon glyphicon-trash" style="color: red"></i></a></td>
    			</tr>
    			<?php endforeach;?>
    		</tbody>
    	</table>
    </div>
    <div class="panel-footer">
    </div>
</div>

<script>
	function deleta(){
		if(confirm("Tem certeza que deseja excluir este registro?")){
			return true;
		} else {
			return false;
		}
}
</script>