<div class="panel panel-primary">
	<div class="panel-heading">
        <div class="panel-title">
            Formação dos Policiais do BPMA
        </div>
    </div>
    <div class="panel-body">
    	<table class="table">
    		<thead>
    			<tr>
    				<th>Nº</th>
    				<th>Policial</th>
    				<th>Lotação</th>
    				<th>Login</th>
    				<th>Perfil</th>
    				<th>Opções</th>
    			</tr>
    		</thead>
    		<tbody>
    		<?php $counter = 1?>
    		<?php foreach ($dados as $item):?>
    			<tr>
    				<td><?php echo $counter++ ?></td>
    				<td><a href="/census/detalhes/<?php echo $item->getPolcodigo()->getCodigo()?>"><?php echo $item->getPolcodigo()->getPostograduacao()?> <?php echo $item->getPolcodigo()->getNomeguerra()?></a></td>
    				<td><?php echo $item->getPolcodigo()->getLotacao()?></td>
    				<td><?php echo $item->getLogin()?></td>
    				<td><?php echo $item->getPercodigo()->getNome()?></td>
    				<td>
    					<a href="/usuario/perfil/<?php echo $item->getCodigo()?>"><i class="glyphicon glyphicon-pencil"></i></a> 
    				</td>
    				
    			</tr>
    			<?php endforeach;?>
    		</tbody>
    	</table>
    </div>
    <div class="panel-footer">
    </div>
</div>

<script>
	function deleta(){
		if(confirm("Tem certeza que deseja excluir este registro?")){
			return true;
		} else {
			return false;
		}
}
</script>