<div class="panel panel-primary">
	<div class="panel-heading">
		<div class="panel-title">
            <h3 class="panel-title"><?php echo $this->policial['postograduacao'] . " " . $this->policial['nomeguerra'] ?> - Lançamento de Punição</h3>
        </div>
    </div>
    <div class="panel-body">
    <?php echo $this->form()->openTag($form); ?>
    	<div class="row">
    		
    		<div class="col-xs-2">
    			<?php echo $this->formRow($form->get('tipo')) ?>
    		</div>
    		<div class="col-xs-1">
    			<?php echo $this->formRow($form->get('quantidadedias')) ?>
    		</div>
    		<div class="col-xs-2">
    			<?php echo $this->formRow($form->get('faltaservico')) ?>
    		</div>
    		<div class="col-xs-4">
    			<?php echo $this->formRow($form->get('apuracao')) ?>
    		</div>
    		<div class="col-xs-3">
    			<?php echo $this->formRow($form->get('dataapuracao')) ?>
    		</div>
    		
    	</div>
    	<div class="row">
    		<div class="col-xs-3">
    			<?php echo $this->formRow($form->get('origem')) ?>
    		</div>
    		<div class="col-xs-3">
    			<?php echo $this->formRow($form->get('datafato')) ?>
    		</div>
    		<div class="col-xs-3">
    			<?php echo $this->formRow($form->get('boletim')) ?>
    		</div>
    		<div class="col-xs-3">
    			<?php echo $this->formRow($form->get('data')) ?>
    		</div>
    	</div>
    	<div class="row">
    		<div class="col-xs-12">
    			<?php echo $this->formRow($form->get('descricao')) ?>
    		</div>
    	</div>
    	<div class="row">
    		
    		<input type="hidden" id="polcodigo" name="polcodigo" value="<?php echo $this->policial['codigo']?>">
    	</div>
    </div>
    <div class="panel-footer">
    <?php echo $this->formSubmit($form->get('submit')) ?>
    </div>
    <?php echo $this->form()->closeTag($form); ?> 
</div>