<div class="card ">
	<div class="header">
		<h4 class="title">Escala de Fiscal</h4>
		<p class="category">Auxiliar do Oficial de Dia ao BPMA</p>
	</div>
	<div class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="table-responsive"></div>
				<table class="table">
					<thead>
						<tr>
							<th></th>
							<th></th>
							<th colspan="31" class="text-center">Janeiro</th>
						</tr>
						<tr>
							<th>Nº</th>
							<th>Nome</th>
							<th class="text-center">01</th>
							<th>02</th>
							<th>03</th>
							<th>04</th>
							<th>05</th>
							<th>06</th>
							<th>07</th>
							<th>08</th>
							<th>09</th>
							<th>10</th>
							<th>11</th>
							<th>12</th>
							<th>13</th>
							<th>14</th>
							<th>15</th>
							<th>16</th>
							<th>17</th>
							<th>18</th>
							<th>19</th>
							<th>20</th>
							<th>21</th>
							<th>22</th>
							<th>23</th>
							<th>24</th>
							<th>25</th>
							<th>26</th>
							<th>27</th>
							<th>28</th>
							<th>29</th>
							<th>30</th>
							<th>31</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th colspan="33">Mês</th>
						</tr>
					</tfoot>
					<tbody>
						<?php $counter = 1;?>
						<?php foreach ($dados as $item):?>
						<tr>
							<th class="text-center"><?php echo $counter++?></th>
							<th><?php echo $item->getPolcodigo()->getPostograduacao() . " " . $item->getPolcodigo()->getNomeguerra()?></th>
							<td class="text-center"><?php if ($item->getEscalado() == '1') echo "Sv"; else echo $item->getQtdfolgas()?></td>
						</tr>
						<?php endforeach;?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>