<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Distribuição do Efetivo do Expediente</h3>
            </div>
            <div class="panel-body">
            <table class="table table-condensed table-bordered">
    			<thead>
      				<tr>
        				<th>Post/Grad</th>
        				<th>SA</th>
        				<th>NGP</th>
        				<th>NCC</th>
        				<th>Sec</th>
        				<th>NCS</th>
        				<th>Prj</th>
        				<th>Alm</th>
        				<th>Man</th>
        				<th>SO</th>
        				<th>Int</th>
        				<th>Neec</th>
        				<th>Nean</th>
        				<th>Capa</th>
        				<th>CAp</th>
        				<th>SvI</th>
        				<th>RM</th>
      				</tr>
    			</thead>
    			<tbody>
    			  <tr>
			        <th class="text-center">TC</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=SAd"><?php echo $this->efetivoSAd['TC'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=NGP"><?php echo $this->efetivoNGP['TC'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=NCC"><?php echo $this->efetivoNCC['TC'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=Sec"><?php echo $this->efetivoSec['TC'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=NCS"><?php echo $this->efetivoNCS['TC'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=NProj"><?php echo $this->efetivoPrj['TC'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=Almox"><?php echo $this->efetivoAlm['TC'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=NMan"><?php echo $this->efetivoMan['TC'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=SOp"><?php echo $this->efetivoSOp['TC'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=SSInt"><?php echo $this->efetivoInt['TC'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=NEEC"><?php echo $this->efetivoNEEC['TC'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=NEAN"><?php echo $this->efetivoNEAN['TC'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=CeAPA"><?php echo $this->efetivoCAPA['TC'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=CiaApoio"><?php echo $this->efetivoCAp['TC'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=ServInter"><?php echo $this->efetivoSvI['TC'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=TC&lotacao=RM"><?php echo $this->efetivoRM['TC'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">Maj</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=SAd"><?php echo $this->efetivoSAd['Maj'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=NGP"><?php echo $this->efetivoNGP['Maj'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=NCC"><?php echo $this->efetivoNCC['Maj'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=Sec"><?php echo $this->efetivoSec['Maj'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=NCS"><?php echo $this->efetivoNCS['Maj'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=NProj"><?php echo $this->efetivoPrj['Maj'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=Almox"><?php echo $this->efetivoAlm['Maj'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=NMan"><?php echo $this->efetivoMan['Maj'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=SOp"><?php echo $this->efetivoSOp['Maj'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=SSInt"><?php echo $this->efetivoInt['Maj'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=NEEC"><?php echo $this->efetivoNEEC['Maj'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=NEAN"><?php echo $this->efetivoNEAN['Maj'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=CeAPA"><?php echo $this->efetivoCAPA['Maj'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=CiaApoio"><?php echo $this->efetivoCAp['Maj'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=ServInter"><?php echo $this->efetivoSvI['Maj'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Maj&lotacao=RM"><?php echo $this->efetivoRM['Maj'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">Cap</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=SAd"><?php echo $this->efetivoSAd['Cap'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=NGP"><?php echo $this->efetivoNGP['Cap'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=NCC"><?php echo $this->efetivoNCC['Cap'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=Sec"><?php echo $this->efetivoSec['Cap'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=NCS"><?php echo $this->efetivoNCS['Cap'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=NProj"><?php echo $this->efetivoPrj['Cap'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=Almox"><?php echo $this->efetivoAlm['Cap'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=NMan"><?php echo $this->efetivoMan['Cap'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=SOp"><?php echo $this->efetivoSOp['Cap'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=SSInt"><?php echo $this->efetivoInt['Cap'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=NEEC"><?php echo $this->efetivoNEEC['Cap'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=NEAN"><?php echo $this->efetivoNEAN['Cap'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=CeAPA"><?php echo $this->efetivoCAPA['Cap'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=CiaApoio"><?php echo $this->efetivoCAp['Cap'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=ServInter"><?php echo $this->efetivoSvI['Cap'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cap&lotacao=RM"><?php echo $this->efetivoRM['Cap'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">1º Ten</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=SAd"><?php echo $this->efetivoSAd['1Ten'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=NGP"><?php echo $this->efetivoNGP['1Ten'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=NCC"><?php echo $this->efetivoNCC['1Ten'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=Sec"><?php echo $this->efetivoSec['1Ten'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=NCS"><?php echo $this->efetivoNCS['1Ten'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=NProj"><?php echo $this->efetivoPrj['1Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=Almox"><?php echo $this->efetivoAlm['1Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=NMan"><?php echo $this->efetivoMan['1Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=SOp"><?php echo $this->efetivoSOp['1Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=SSInt"><?php echo $this->efetivoInt['1Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=NEEC"><?php echo $this->efetivoNEEC['1Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=NEAN"><?php echo $this->efetivoNEAN['1Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=CeAPA"><?php echo $this->efetivoCAPA['1Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=CiaApoio"><?php echo $this->efetivoCAp['1Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=ServInter"><?php echo $this->efetivoSvI['1Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Ten&lotacao=RM"><?php echo $this->efetivoRM['1Ten'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">2º Ten</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=SAd"><?php echo $this->efetivoSAd['2Ten'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=NGP"><?php echo $this->efetivoNGP['2Ten'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=NCC"><?php echo $this->efetivoNCC['2Ten'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=Sec"><?php echo $this->efetivoSec['2Ten'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=NCS"><?php echo $this->efetivoNCS['2Ten'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=NProj"><?php echo $this->efetivoPrj['2Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=Almox"><?php echo $this->efetivoAlm['2Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=NMan"><?php echo $this->efetivoMan['2Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=SOp"><?php echo $this->efetivoSOp['2Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=SSInt"><?php echo $this->efetivoInt['2Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=NEEC"><?php echo $this->efetivoNEEC['2Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=NEAN"><?php echo $this->efetivoNEAN['2Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=CeAPA"><?php echo $this->efetivoCAPA['2Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=CiaApoio"><?php echo $this->efetivoCAp['2Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=ServInter"><?php echo $this->efetivoSvI['2Ten'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Ten&lotacao=RM"><?php echo $this->efetivoRM['2Ten'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">ST</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=SAd"><?php echo $this->efetivoSAd['ST'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=NGP"><?php echo $this->efetivoNGP['ST'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=NCC"><?php echo $this->efetivoNCC['ST'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=Sec"><?php echo $this->efetivoSec['ST'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=NCS"><?php echo $this->efetivoNCS['ST'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=NProj"><?php echo $this->efetivoPrj['ST'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=Almox"><?php echo $this->efetivoAlm['ST'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=NMan"><?php echo $this->efetivoMan['ST'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=SOp"><?php echo $this->efetivoSOp['ST'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=SSInt"><?php echo $this->efetivoInt['ST'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=NEEC"><?php echo $this->efetivoNEEC['ST'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=NEAN"><?php echo $this->efetivoNEAN['ST'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=CeAPA"><?php echo $this->efetivoCAPA['ST'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=CiaApoio"><?php echo $this->efetivoCAp['ST'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=ServInter"><?php echo $this->efetivoSvI['ST'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=ST&lotacao=RM"><?php echo $this->efetivoRM['ST'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">1º Sgt</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=SAd"><?php echo $this->efetivoSAd['1Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=NGP"><?php echo $this->efetivoNGP['1Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=NCC"><?php echo $this->efetivoNCC['1Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=Sec"><?php echo $this->efetivoSec['1Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=NCS"><?php echo $this->efetivoNCS['1Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=NProj"><?php echo $this->efetivoPrj['1Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=Almox"><?php echo $this->efetivoAlm['1Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=NMan"><?php echo $this->efetivoMan['1Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=SOp"><?php echo $this->efetivoSOp['1Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=SSInt"><?php echo $this->efetivoInt['1Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=NEEC"><?php echo $this->efetivoNEEC['1Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=NEAN"><?php echo $this->efetivoNEAN['1Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=CeAPA"><?php echo $this->efetivoCAPA['1Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=CiaApoio"><?php echo $this->efetivoCAp['1Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=ServInter"><?php echo $this->efetivoSvI['1Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=1º Sgt&lotacao=RM"><?php echo $this->efetivoRM['1Sgt'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">2º Sgt</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=SAd"><?php echo $this->efetivoSAd['2Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=NGP"><?php echo $this->efetivoNGP['2Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=NCC"><?php echo $this->efetivoNCC['2Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=Sec"><?php echo $this->efetivoSec['2Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=NCS"><?php echo $this->efetivoNCS['2Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=NProj"><?php echo $this->efetivoPrj['2Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=Almox"><?php echo $this->efetivoAlm['2Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=NMan"><?php echo $this->efetivoMan['2Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=SOp"><?php echo $this->efetivoSOp['2Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=SSInt"><?php echo $this->efetivoInt['2Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=NEEC"><?php echo $this->efetivoNEEC['2Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=NEAN"><?php echo $this->efetivoNEAN['2Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=CeAPA"><?php echo $this->efetivoCAPA['2Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=CiaApoio"><?php echo $this->efetivoCAp['2Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=ServIner"><?php echo $this->efetivoSvI['2Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=2º Sgt&lotacao=RM"><?php echo $this->efetivoRM['2Sgt'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">3º Sgt</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=SAd"><?php echo $this->efetivoSAd['3Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=NGP"><?php echo $this->efetivoNGP['3Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=NCC"><?php echo $this->efetivoNCC['3Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=Sec"><?php echo $this->efetivoSec['3Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=NCS"><?php echo $this->efetivoNCS['3Sgt'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=NProj"><?php echo $this->efetivoPrj['3Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=Almox"><?php echo $this->efetivoAlm['3Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=NMan"><?php echo $this->efetivoMan['3Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=SOp"><?php echo $this->efetivoSOp['3Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=SSInt"><?php echo $this->efetivoInt['3Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=NEEC"><?php echo $this->efetivoNEEC['3Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=NEAN"><?php echo $this->efetivoNEAN['3Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=CeAPA"><?php echo $this->efetivoCAPA['3Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=CiaApoio"><?php echo $this->efetivoCAp['3Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=ServInter"><?php echo $this->efetivoSvI['3Sgt'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=3º Sgt&lotacao=RM"><?php echo $this->efetivoRM['3Sgt'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">Cb</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=SAd"><?php echo $this->efetivoSAd['Cb'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=NGP"><?php echo $this->efetivoNGP['Cb'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=NCC"><?php echo $this->efetivoNCC['Cb'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=Sec"><?php echo $this->efetivoSec['Cb'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=NCS"><?php echo $this->efetivoNCS['Cb'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=NProj"><?php echo $this->efetivoPrj['Cb'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=Almox"><?php echo $this->efetivoAlm['Cb'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=NMan"><?php echo $this->efetivoMan['Cb'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=SOp"><?php echo $this->efetivoSOp['Cb'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=SSInt"><?php echo $this->efetivoInt['Cb'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=NEEC"><?php echo $this->efetivoNEEC['Cb'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=NEAN"><?php echo $this->efetivoNEAN['Cb'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=CeAPA"><?php echo $this->efetivoCAPA['Cb'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=CiaApoio"><?php echo $this->efetivoCAp['Cb'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=ServInter"><?php echo $this->efetivoSvI['Cb'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Cb&lotacao=RM"><?php echo $this->efetivoRM['Cb'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">Sd</th>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=SAd"><?php echo $this->efetivoSAd['Sd'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=NGP"><?php echo $this->efetivoNGP['Sd'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=NCC"><?php echo $this->efetivoNCC['Sd'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=Sec"><?php echo $this->efetivoSec['Sd'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=NCS"><?php echo $this->efetivoNCS['Sd'] ?></a></td>
			        <td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=NProj"><?php echo $this->efetivoPrj['Sd'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=Almox"><?php echo $this->efetivoAlm['Sd'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=NMan"><?php echo $this->efetivoMan['Sd'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=SOp"><?php echo $this->efetivoSOp['Sd'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=SSInt"><?php echo $this->efetivoInt['Sd'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=NEEC"><?php echo $this->efetivoNEEC['Sd'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=NEAN"><?php echo $this->efetivoNEAN['Sd'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=CeAPA"><?php echo $this->efetivoCAPA['Sd'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=CiaApoio"><?php echo $this->efetivoCAp['Sd'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=ServIner"><?php echo $this->efetivoSvI['Sd'] ?></a></td>
					<td class="text-center"><a href="/mapa/listarSub?postgrad=Sd&lotacao=RM"><?php echo $this->efetivoRM['Sd'] ?></a></td>
			      </tr>
			      <tr>
			        <th class="text-center">Total</th>
			        <th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=SAd"><?php echo $this->efetivoSAd['Total'] ?></a></th>
			        <th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=NGP"><?php echo $this->efetivoNGP['Total'] ?></a></th>
			        <th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=NCC"><?php echo $this->efetivoNCC['Total'] ?></a></th>
			        <th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=Sec"><?php echo $this->efetivoSec['Total'] ?></a></th>
			        <th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=NCS"><?php echo $this->efetivoNCS['Total'] ?></a></th>
			        <th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=NProj"><?php echo $this->efetivoPrj['Total'] ?></a></th>
					<th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=Almox"><?php echo $this->efetivoAlm['Total'] ?></a></th>
					<th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=NMan"><?php echo $this->efetivoMan['Total'] ?></a></th>
					<th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=SOp"><?php echo $this->efetivoSOp['Total'] ?></a></th>
					<th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=SSInt"><?php echo $this->efetivoInt['Total'] ?></a></th>
					<th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=NEEC"><?php echo $this->efetivoNEEC['Total'] ?></a></th>
					<th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=NEAN"><?php echo $this->efetivoNEAN['Total'] ?></a></th>
					<th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=CeAPA"><?php echo $this->efetivoCAPA['Total'] ?></a></th>
					<th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=CiaApoio"><?php echo $this->efetivoCAp['Total'] ?></a></th>
					<th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=ServInter"><?php echo $this->efetivoSvI['Total'] ?></a></th>
					<th class="text-center"><a href="/mapa/listarSub?postgrad=todos&lotacao=RM"><?php echo $this->efetivoRM['Total'] ?></a></th>
			      </tr>

			      </tbody>
			  </table>
			  <table class="table table-condensed table-bordered">
			  <tbody>
			       <tr>
			        <th>Sem Classificação: <a href="mapa/listar?postgrad=all&lotacao=semclas"><?php //echo $this->efetivoTotal['SemClass'] ?></a></th>
			      </tr>
			    </tbody>
			  </table>
            </div>
        </div>
    </div>
</div>
