<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Distribuição do Efetivo do BPMA') ?></h3>
            </div>
            <div class="panel-body">
            <table class="table table-condensed table-bordered">
    			<thead>
      				<tr>
        				<th>Post/Grad</th>
        				<th><a href="/mapa/batalhao">Batalhão</a></th>
        				<th><a href="/mapa/goa">GOA</a></th>
        				<th>GPTur</th>
        				<th>Cia Sul</th>
        				<th>Cia Leste</th>
        				<th>Cia Oeste</th>
        				<th>TOTAL</th>
        				<th>TOTAL Geral</th>
      				</tr>
    			</thead>
    			<tbody>
    			  <tr>
			        <th class="text-center">TC</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=TC&lotacao=Btl"><?php echo $this->efetivoBtl['TC'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=TC&lotacao=goa"><?php echo $this->efetivoGoa['TC'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=TC&lotacao=GPTur"><?php echo $this->efetivoGptur['TC'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=TC&lotacao=CiaSul"><?php echo $this->efetivoCiasul['TC'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=TC&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['TC'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=TC&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['TC'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['TC']+$this->efetivoGoa['TC']+$this->efetivoGptur['TC']+$this->efetivoCiasul['TC']+$this->efetivoCialeste['TC']+$this->efetivoCiaoeste['TC'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=TC&lotacao=total"><?php echo $this->efetivoTotal['TC'] ?></a></th>
			      </tr>
			      <tr class="text-center">
			        <th class="text-center">Maj</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=Maj&lotacao=Btl"><?php echo $this->efetivoBtl['Maj'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Maj&lotacao=goa"><?php echo $this->efetivoGoa['Maj'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Maj&lotacao=GPTur"><?php echo $this->efetivoGptur['Maj'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Maj&lotacao=CiaSul"><?php echo $this->efetivoCiasul['Maj'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Maj&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['Maj'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Maj&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['Maj'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['Maj']+$this->efetivoGoa['Maj']+$this->efetivoGptur['Maj']+$this->efetivoCiasul['Maj']+$this->efetivoCialeste['Maj']+$this->efetivoCiaoeste['Maj'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=Maj&lotacao=total"><?php echo $this->efetivoTotal['Maj'] ?></a></th>
			      </tr>
			      <tr class="text-center">
			        <th class="text-center">Cap</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cap&lotacao=Btl"><?php echo $this->efetivoBtl['Cap'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cap&lotacao=goa"><?php echo $this->efetivoGoa['Cap'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cap&lotacao=GPTur"><?php echo $this->efetivoGptur['Cap'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cap&lotacao=CiaSul"><?php echo $this->efetivoCiasul['Cap'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cap&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['Cap'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cap&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['Cap'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['Cap']+$this->efetivoGoa['Cap']+$this->efetivoGptur['Cap']+$this->efetivoCiasul['Cap']+$this->efetivoCialeste['Cap']+$this->efetivoCiaoeste['Cap'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=Cap&lotacao=total"><?php echo $this->efetivoTotal['Cap'] ?></a></th>
			      </tr>
			      <tr class="text-center">
			        <th class="text-center">1º Ten</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Ten&lotacao=Btl"><?php echo $this->efetivoBtl['1Ten'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Ten&lotacao=goa"><?php echo $this->efetivoGoa['1Ten'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Ten&lotacao=GPTur"><?php echo $this->efetivoGptur['1Ten'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Ten&lotacao=CiaSul"><?php echo $this->efetivoCiasul['1Ten'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Ten&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['1Ten'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Ten&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['1Ten'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['1Ten']+$this->efetivoGoa['1Ten']+$this->efetivoGptur['1Ten']+$this->efetivoCiasul['1Ten']+$this->efetivoCialeste['1Ten']+$this->efetivoCiaoeste['1Ten'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=1º Ten&lotacao=total"><?php echo $this->efetivoTotal['1Ten'] ?></a></th>
			      </tr>
			      <tr>
			        <th class="text-center">2º Ten</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Ten&lotacao=Btl"><?php echo $this->efetivoBtl['2Ten'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Ten&lotacao=goa"><?php echo $this->efetivoGoa['2Ten'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Ten&lotacao=GPTur"><?php echo $this->efetivoGptur['2Ten'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Ten&lotacao=CiaSul"><?php echo $this->efetivoCiasul['2Ten'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Ten&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['2Ten'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Ten&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['2Ten'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['2Ten']+$this->efetivoGoa['2Ten']+$this->efetivoGptur['2Ten']+$this->efetivoCiasul['2Ten']+$this->efetivoCialeste['2Ten']+$this->efetivoCiaoeste['2Ten'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=2º Ten&lotacao=total"><?php echo $this->efetivoTotal['2Ten'] ?></a></th>
			      </tr>
			      <tr>
			        <th class="text-center">ST</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=ST&lotacao=Btl"><?php echo $this->efetivoBtl['ST'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=ST&lotacao=goa"><?php echo $this->efetivoGoa['ST'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=ST&lotacao=GPTur"><?php echo $this->efetivoGptur['ST'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=ST&lotacao=CiaSul"><?php echo $this->efetivoCiasul['ST'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=ST&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['ST'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=ST&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['ST'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['ST']+$this->efetivoGoa['ST']+$this->efetivoGptur['ST']+$this->efetivoCiasul['ST']+$this->efetivoCialeste['ST']+$this->efetivoCiaoeste['ST'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=ST&lotacao=total"><?php echo $this->efetivoTotal['ST'] ?></a></th>
			      </tr>
			      <tr>
			        <th class="text-center">1º Sgt</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Sgt&lotacao=Btl"><?php echo $this->efetivoBtl['1Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Sgt&lotacao=goa"><?php echo $this->efetivoGoa['1Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Sgt&lotacao=GPTur"><?php echo $this->efetivoGptur['1Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Sgt&lotacao=CiaSul"><?php echo $this->efetivoCiasul['1Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Sgt&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['1Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=1º Sgt&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['1Sgt'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['1Sgt']+$this->efetivoGoa['1Sgt']+$this->efetivoGptur['1Sgt']+$this->efetivoCiasul['1Sgt']+$this->efetivoCialeste['1Sgt']+$this->efetivoCiaoeste['1Sgt'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=1º Sgt&lotacao=total"><?php echo $this->efetivoTotal['1Sgt'] ?></a></th>
			      </tr>
			      <tr>
			        <th class="text-center">2º Sgt</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Sgt&lotacao=Btl"><?php echo $this->efetivoBtl['2Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Sgt&lotacao=goa"><?php echo $this->efetivoGoa['2Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Sgt&lotacao=GPTur"><?php echo $this->efetivoGptur['2Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Sgt&lotacao=CiaSul"><?php echo $this->efetivoCiasul['2Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Sgt&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['2Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=2º Sgt&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['2Sgt'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['2Sgt']+$this->efetivoGoa['2Sgt']+$this->efetivoGptur['2Sgt']+$this->efetivoCiasul['2Sgt']+$this->efetivoCialeste['2Sgt']+$this->efetivoCiaoeste['2Sgt'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=2º Sgt&lotacao=total"><?php echo $this->efetivoTotal['2Sgt'] ?></a></th>
			      </tr>
			      <tr>
			        <th class="text-center">3º Sgt</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=3º Sgt&lotacao=Btl"><?php echo $this->efetivoBtl['3Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=3º Sgt&lotacao=goa"><?php echo $this->efetivoGoa['3Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=3º Sgt&lotacao=GPTur"><?php echo $this->efetivoGptur['3Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=3º Sgt&lotacao=CiaSul"><?php echo $this->efetivoCiasul['3Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=3º Sgt&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['3Sgt'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=3º Sgt&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['3Sgt'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['3Sgt']+$this->efetivoGoa['3Sgt']+$this->efetivoGptur['3Sgt']+$this->efetivoCiasul['3Sgt']+$this->efetivoCialeste['3Sgt']+$this->efetivoCiaoeste['3Sgt'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=3º Sgt&lotacao=total"><?php echo $this->efetivoTotal['3Sgt'] ?></a></th>
			      </tr>
			      <tr>
			        <th class="text-center">Cb</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cb&lotacao=Btl"><?php echo $this->efetivoBtl['Cb'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cb&lotacao=goa"><?php echo $this->efetivoGoa['Cb'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cb&lotacao=GPTur"><?php echo $this->efetivoGptur['Cb'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cb&lotacao=CiaSul"><?php echo $this->efetivoCiasul['Cb'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cb&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['Cb'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Cb&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['Cb'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['Cb']+$this->efetivoGoa['Cb']+$this->efetivoGptur['Cb']+$this->efetivoCiasul['Cb']+$this->efetivoCialeste['Cb']+$this->efetivoCiaoeste['Cb'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=Cb&lotacao=total"><?php echo $this->efetivoTotal['Cb'] ?></a></th>
			      </tr>
			      <tr>
			      <tr>
			        <th class="text-center">Sd</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=Sd&lotacao=Btl"><?php echo $this->efetivoBtl['Sd'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Sd&lotacao=goa"><?php echo $this->efetivoGoa['Sd'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Sd&lotacao=GPTur"><?php echo $this->efetivoGptur['Sd'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Sd&lotacao=CiaSul"><?php echo $this->efetivoCiasul['Sd'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Sd&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['Sd'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=Sd&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['Sd'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['Sd']+$this->efetivoGoa['Sd']+$this->efetivoGptur['Sd']+$this->efetivoCiasul['Sd']+$this->efetivoCialeste['Sd']+$this->efetivoCiaoeste['Sd'] ?></td>
			        <th class="text-center"><a href="mapa/listar?postgrad=Sd&lotacao=total"><?php echo $this->efetivoTotal['Sd'] ?></a></th>
			      </tr>
			      <tr>
			        <th class="text-center">Total</th>
			        <td class="text-center"><a href="mapa/listar?postgrad=todos&lotacao=Btl"><?php echo $this->efetivoBtl['Total'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=todos&lotacao=GOA"><?php echo $this->efetivoGoa['Total'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=todos&lotacao=GPTur"><?php echo $this->efetivoGptur['Total'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=todos&lotacao=CiaSul"><?php echo $this->efetivoCiasul['Total'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=todos&lotacao=CiaLeste"><?php echo $this->efetivoCialeste['Total'] ?></a></td>
			        <td class="text-center"><a href="mapa/listar?postgrad=todos&lotacao=CiaOeste"><?php echo $this->efetivoCiaoeste['Total'] ?></a></td>
			        <td class="text-center"><?php echo $this->efetivoBtl['Total']+$this->efetivoGoa['Total']+$this->efetivoGptur['Total']+$this->efetivoCiasul['Total']+$this->efetivoCialeste['Total']+$this->efetivoCiaoeste['Total'] ?></td>
			        <th class="text-center"><?php echo $this->efetivoTotal['Total'] ?></th>
			      </tr>

			      </tbody>
			  </table>
			  <table class="table table-condensed table-bordered">
			  <tbody>
			       <tr>
			        <th>Sem lotação na SubUnidade: <a href="mapa/listar?postgrad=all&lotacao=semclas"><?php echo $this->efetivoTotal['SemClass'] ?></a></th>
			      </tr>
			    </tbody>
			  </table>
            </div>
        </div>
    </div>
</div>
