				<div class="row">                   
                    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                        <form method="#" action="#">
                            
                        <!--   if you want to have the card without animation please remove the ".card-hidden" class   -->
                            <div class="card card-hidden">
                                <div class="header text-center">Autenticação Necessária</div>
                                <div class="content">
                                    <div class="form-group">
                                        <label>Usuário</label>
                                        <input type="text" placeholder="Digite seu usuário" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>Senha</label>
                                        <input type="password" placeholder="Senha" class="form-control">
                                    </div>                                    
                                    <div class="form-group">
                                           
                                    </div>
                                </div>
                                <div class="footer text-center">
                                    <button type="submit" class="btn btn-fill btn-warning btn-wd">Entrar</button>
                                </div>
                            </div>
                                
                        </form>
                                
                    </div>                    
                </div>